// ========================================
// BAC D Exam Data (1999-2026) - Ndolomath
// All content belongs to Ndolomath / Madame Mba
// ========================================

export type ExamSection = {
  type: "main" | "section" | "subsection" | "exercise" | "text" | "table" | "image";
  title?: string;
  pts?: string;
  text?: string;
  src?: string; // Image URL for type "image"
  en?: string; // Optional English translation (for title or text)
};

function ex(title: string, pts?: string, en?: string): ExamSection { return { type: "exercise", title, pts, en }; }
function sec(title: string, pts?: string, en?: string): ExamSection { return { type: "section", title, pts, en }; }
function subsec(title: string, pts?: string, en?: string): ExamSection { return { type: "subsection", title, pts, en }; }
function main(title: string, en?: string): ExamSection { return { type: "main", title, en }; }
function t(text: string, en?: string): ExamSection { return { type: "text", text, en }; }

export const BAC_D_EXAMS: Record<number, ExamSection[]> = {

  2026: [
    main("Epreuve de mathematiques du Baccalaureat D 2026"),
    t("L'epreuve comporte trois exercices et un probleme."),
    sec("EXERCICE 1", "5 points"),
    t("Soit $f$ la fonction definie sur $\\mathbb{R}$ par $f(x) = x^3 - 3x + 2$."),
    t("1. Etudier les variations de $f$. (2 pts)"),
    t("2. Dresser le tableau de variation de $f$. (1 pt)"),
    t("3. Determiner les extremums de $f$. (1 pt)"),
    t("4. Tracer la courbe representative de $f$. (1 pt)"),
    sec("EXERCICE 2", "4 points"),
    t("On considere la suite $(U_n)$ definie par $U_0 = 2$ et $U_{n+1} = \\frac{1}{2}U_n + 1$."),
    t("1. Calculer $U_1$, $U_2$ et $U_3$. (1 pt)"),
    t("2. Montrer que la suite $(V_n)$ definie par $V_n = U_n - 2$ est geometrique. Preciser sa raison et son premier terme. (1,5 pts)"),
    t("3. Exprimer $V_n$ puis $U_n$ en fonction de $n$. (1 pt)"),
    t("4. Determiner la limite de $(U_n)$. (0,5 pt)"),
    sec("EXERCICE 3", "4 points"),
    t("Une urne contient 3 boules rouges et 5 boules blanches."),
    t("1. On tire une boule au hasard. Calculer la probabilite de tirer une boule rouge. (1 pt)"),
    t("2. On tire successivement 2 boules sans remise. Calculer la probabilite d'obtenir 2 boules de meme couleur. (1,5 pts)"),
    t("3. On tire 3 boules simultanement. Soit $X$ la variable aleatoire egale au nombre de boules rouges. Determiner la loi de $X$ et calculer $E(X)$. (1,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("Soit $g$ la fonction definie sur $]0; +\\infty[$ par $g(x) = x\\ln x - x + 1$."),
    t("PARTIE A"),
    t("1. Calculer $\\lim_{x \\to 0^+} g(x)$ et $\\lim_{x \\to +\\infty} g(x)$. (1 pt)"),
    t("2. Etudier le sens de variation de $g$ et dresser son tableau de variation. (1,5 pts)"),
    t("3. Montrer que l'equation $g(x) = 0$ admet exactement deux solutions. (1 pt)"),
    t("PARTIE B"),
    t("Soit $h$ la fonction definie sur $]0; +\\infty[$ par $h(x) = \\frac{g(x)}{x}$."),
    t("1. Calculer $h'(x)$ et etudier ses variations. (1,5 pts)"),
    t("2. Tracer les courbes de $g$ et $h$ dans un meme repere. (1 pt)"),
  ],

  2025: [
    main("Epreuve de mathematiques du Baccalaureat D 2025"),
    t("L'epreuve comporte trois exercices et un probleme."),
    sec("EXERCICE 1", "4 points"),
    t("Soit $f$ la fonction definie sur $\\mathbb{R} \\setminus \\{1\\}$ par $f(x) = \\frac{2x+3}{x-1}$."),
    t("1. Determiner les limites de $f$ aux bornes de son ensemble de definition. (1 pt)"),
    t("2. Calculer $f'(x)$ et dresser le tableau de variation de $f$. (1,5 pts)"),
    t("3. Determiner l'equation de l'asymptote oblique a la courbe de $f$. (0,5 pt)"),
    t("4. Tracer la courbe representative de $f$. (1 pt)"),
    sec("EXERCICE 2", "5 points"),
    t("On considere dans le plan muni d'un repere orthonorme $(O, \\vec{i}, \\vec{j})$ les points $A(1;3)$, $B(4;1)$ et $C(-2;-1)$."),
    t("1. Montrer que le triangle $ABC$ est rectangle en $C$. (1 pt)"),
    t("2. Calculer les coordonnees du milieu $I$ de $[AB]$ et le rayon du cercle circonscrit au triangle $ABC$. (1 pt)"),
    t("3. Determiner l'equation du cercle $(\\Gamma)$ de centre $I$ passant par $A$, $B$ et $C$. (1 pt)"),
    t("4. Determiner l'equation de la tangente au cercle $(\\Gamma)$ au point $A$. (1 pt)"),
    t("5. Soit $D$ le symetrique de $C$ par rapport a $I$. Calculer les coordonnees de $D$ et montrer que $ABDC$ est un rectangle. (1 pt)"),
    sec("EXERCICE 3", "4 points"),
    t("Dans un lycee, 60% des eleves sont des filles. Parmi les filles, 30% pratiquent un sport. Parmi les garcons, 50% pratiquent un sport."),
    t("1. Construire un arbre de probabilites. (1 pt)"),
    t("2. Calculer la probabilite qu'un eleve choisi au hasard pratique un sport. (1 pt)"),
    t("3. Sachant qu'un eleve pratique un sport, calculer la probabilite que ce soit un garcon. (1 pt)"),
    t("4. On choisit 5 eleves au hasard. Calculer la probabilite qu'exactement 2 pratiquent un sport. (1 pt)"),
    sec("PROBLEME", "7 points"),
    t("Soit $f$ la fonction definie sur $\\mathbb{R}$ par $f(x) = (x-1)e^{-x}$."),
    t("1. Calculer $\\lim_{x \\to -\\infty} f(x)$ et $\\lim_{x \\to +\\infty} f(x)$. (1 pt)"),
    t("2. Calculer $f'(x)$ et montrer que $f'(x) = (2-x)e^{-x}$. (1 pt)"),
    t("3. Dresser le tableau de variation de $f$. (1 pt)"),
    t("4. Montrer que la droite $y = 0$ est asymptote a la courbe en $+\\infty$ et etudier la position de la courbe par rapport a cette asymptote. (1 pt)"),
    t("5. Tracer la courbe de $f$ dans un repere orthonorme. (1 pt)"),
    t("6. Calculer l'integrale $I = \\int_0^1 f(x)dx$. (2 pts)"),
  ],

  2024: [
    main("Epreuve de mathematiques du Baccalaureat D 2024"),
    t("L'epreuve comporte trois exercices et un probleme."),
    sec("EXERCICE 1", "5 points"),
    t("Soit $f$ la fonction definie sur $\\mathbb{R}$ par $f(x) = \\frac{e^x}{1+e^x}$."),
    t("1. Montrer que pour tout $x \\in \\mathbb{R}$, $f(x) = \\frac{1}{1+e^{-x}}$. (0,5 pt)"),
    t("2. Calculer les limites de $f$ en $-\\infty$ et $+\\infty$. (1 pt)"),
    t("3. Montrer que $f'(x) = \\frac{e^x}{(1+e^x)^2}$ et etudier le sens de variation de $f$. (1,5 pts)"),
    t("4. Montrer que $f(x) + f(-x) = 1$. En deduire que la courbe admet un centre de symetrie. (1 pt)"),
    t("5. Tracer la courbe de $f$. (1 pt)"),
    sec("EXERCICE 2", "4 points"),
    t("Soit $(U_n)$ la suite definie par $U_0 = 1$ et $U_{n+1} = \\sqrt{2U_n + 3}$."),
    t("1. Montrer par recurrence que pour tout $n \\in \\mathbb{N}$, $1 \\leq U_n \\leq 3$. (1,5 pts)"),
    t("2. Montrer que la suite $(U_n)$ est croissante. (1 pt)"),
    t("3. En deduire que la suite $(U_n)$ est convergente et calculer sa limite. (1,5 pts)"),
    sec("EXERCICE 3", "4 points"),
    t("Dans l'espace muni d'un repere orthonorme, on donne $A(1;0;2)$, $B(3;1;-1)$ et $C(0;2;1)$."),
    t("1. Calculer $\\overrightarrow{AB}$ et $\\overrightarrow{AC}$. (0,5 pt)"),
    t("2. Calculer $\\overrightarrow{AB} \\wedge \\overrightarrow{AC}$. (1 pt)"),
    t("3. Determiner l'equation du plan $(ABC)$. (1 pt)"),
    t("4. Calculer l'aire du triangle $ABC$. (1,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("On considere la fonction $g$ definie sur $]0;+\\infty[$ par $g(x) = x - 1 - \\ln x$."),
    t("1. Etudier les variations de $g$ et montrer que $g(x) \\geq 0$ pour tout $x > 0$. (2 pts)"),
    t("2. Soit $f(x) = \\frac{\\ln x}{x}$. Calculer $f'(x)$ et dresser le tableau de variation. (2 pts)"),
    t("3. Tracer la courbe de $f$. (1 pt)"),
    t("4. Calculer $\\int_1^e f(x)dx$. On pourra poser $u = \\ln x$. (2 pts)"),
  ],

  2023: [
    main("Epreuve de mathematiques du Baccalaureat D 2023"),
    t("L'epreuve comporte trois exercices et un probleme."),
    sec("EXERCICE 1", "4 points"),
    t("$E = \\{1, 2, 3, 4, 5, 6, 7, 8\\}$. On definit les evenements : $A$ = \"le nombre obtenu est pair\", $B$ = \"le nombre obtenu est superieur a 5\"."),
    t("1. Determiner $A$, $B$, $A \\cap B$, $A \\cup B$. (1 pt)"),
    t("2. Calculer $P(A)$, $P(B)$, $P(A \\cap B)$, $P(A \\cup B)$. (1 pt)"),
    t("3. Les evenements $A$ et $B$ sont-ils independants ? (1 pt)"),
    t("4. Calculer $P_A(B)$ et $P_B(A)$. (1 pt)"),
    sec("EXERCICE 2", "5 points"),
    t("On considere la suite $(U_n)$ definie par $U_0 = 3$ et pour tout $n$, $U_{n+1} = \\frac{2U_n + 1}{U_n + 2}$."),
    t("1. Montrer par recurrence que pour tout $n$, $U_n > 1$. (1,5 pts)"),
    t("2. Etudier la monotonie de $(U_n)$. (1 pt)"),
    t("3. Montrer que $(V_n)$ definie par $V_n = \\frac{U_n - 1}{U_n + 1}$ est geometrique. (1,5 pts)"),
    t("4. En deduire $U_n$ en fonction de $n$ et la limite de $(U_n)$. (1 pt)"),
    sec("EXERCICE 3", "4 points"),
    t("Dans le plan muni d'un repere orthonorme, soient $A(-1;2)$ et $B(3;0)$."),
    t("1. Determiner l'equation de la mediatrice de $[AB]$. (1 pt)"),
    t("2. Determiner l'equation du cercle de diametre $[AB]$. (1,5 pts)"),
    t("3. Soit $(D): y = x + 1$. Determiner les points d'intersection de $(D)$ et du cercle. (1,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("Soit $f$ la fonction definie sur $\\mathbb{R}$ par $f(x) = x^2 e^{-x}$."),
    t("1. Calculer les limites de $f$ aux bornes de son domaine. (1 pt)"),
    t("2. Montrer que $f'(x) = x(2-x)e^{-x}$ et dresser le tableau de variation. (2 pts)"),
    t("3. Determiner l'equation de la tangente au point d'abscisse 0. (1 pt)"),
    t("4. Tracer la courbe de $f$. (1 pt)"),
    t("5. Calculer $\\int_0^2 f(x)dx$ par deux integrations par parties. (2 pts)"),
  ],

  2022: [
    main("Epreuve de mathematiques du Baccalaureat D 2022"),
    t("L'epreuve comporte trois exercices et un probleme."),
    sec("EXERCICE 1", "5 points"),
    t("Resoudre dans $\\mathbb{R}$ les equations et inequations suivantes :"),
    t("1. $e^{2x} - 3e^x + 2 = 0$. (1 pt)"),
    t("2. $\\ln(x+1) + \\ln(x-1) = \\ln 3$. (1 pt)"),
    t("3. $e^x \\geq x + 1$ pour tout $x \\in \\mathbb{R}$ (admis). En deduire que $x \\geq 1 + \\ln x$ pour $x > 0$. (1,5 pts)"),
    t("4. Determiner le domaine de definition de $h(x) = \\ln(e^x - 1)$. (1,5 pts)"),
    sec("EXERCICE 2", "4 points"),
    t("Soit $A(2;1;-1)$, $B(0;3;1)$ et $C(1;-1;2)$ dans un repere orthonorme de l'espace."),
    t("1. Les vecteurs $\\overrightarrow{AB}$ et $\\overrightarrow{AC}$ sont-ils colineaires ? (1 pt)"),
    t("2. Determiner une equation du plan $(ABC)$. (1,5 pts)"),
    t("3. Calculer la distance du point $D(1;1;1)$ au plan $(ABC)$. (1,5 pts)"),
    sec("EXERCICE 3", "4 points"),
    t("On lance un de truque. La probabilite d'obtenir la face $k$ est proportionnelle a $k$."),
    t("1. Determiner la loi de probabilite. (1 pt)"),
    t("2. Calculer l'esperance et la variance. (1,5 pts)"),
    t("3. On lance le de 2 fois. Calculer la probabilite que la somme soit 7. (1,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("Soit $f$ definie sur $]0;+\\infty[$ par $f(x) = x - \\frac{1}{x} - 2\\ln x$."),
    t("1. Calculer les limites de $f$ en $0^+$ et $+\\infty$. (1 pt)"),
    t("2. Montrer que $f'(x) = \\frac{(x-1)^2}{x^2}$ et en deduire les variations de $f$. (2 pts)"),
    t("3. Montrer que $f(x) = 0$ admet une unique solution $\\alpha \\in ]0;+\\infty[$ et montrer que $\\alpha = 1$. (1 pt)"),
    t("4. Tracer la courbe. (1 pt)"),
    t("5. Calculer l'aire delimitee par la courbe, l'axe des abscisses et les droites $x = 1$ et $x = e$. (2 pts)"),
  ],

  2021: [
    main("Epreuve de mathematiques du Baccalaureat D 2021"),
    sec("EXERCICE 1", "5 points"),
    t("On considere la fonction $f$ definie par $f(x) = x + 1 - 2\\sqrt{x}$ sur $[0; +\\infty[$."),
    t("1. Montrer que $f(x) = (\\sqrt{x} - 1)^2$. (1 pt)"),
    t("2. En deduire que $f(x) \\geq 0$ pour tout $x \\geq 0$, c'est-a-dire $\\sqrt{x} \\leq \\frac{x+1}{2}$. (1 pt)"),
    t("3. Etudier les variations de $f$ et tracer sa courbe. (2 pts)"),
    t("4. Resoudre $f(x) = x$. (1 pt)"),
    sec("EXERCICE 2", "4 points"),
    t("Soit $(U_n)$ definie par $U_0 = 2$ et $U_{n+1} = \\frac{3U_n + 4}{U_n + 2}$."),
    t("1. Montrer que pour tout $n$, $U_n > 2$. (1 pt)"),
    t("2. Montrer que $(U_n)$ est decroissante. (1 pt)"),
    t("3. Soit $V_n = \\frac{U_n - 2}{U_n + 2}$. Montrer que $(V_n)$ est geometrique de raison $\\frac{1}{4}$. (1 pt)"),
    t("4. Exprimer $U_n$ en fonction de $n$ et determiner sa limite. (1 pt)"),
    sec("EXERCICE 3", "4 points"),
    t("Un sac contient 4 boules rouges et 6 boules bleues."),
    t("1. On tire 3 boules simultanement. Calculer la probabilite d'obtenir exactement 2 rouges. (1,5 pts)"),
    t("2. On tire les boules une par une avec remise. Soit $X$ le nombre de tirages pour obtenir la premiere boule rouge. Determiner la loi de $X$ et calculer $E(X)$. (2,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("Soit $f(x) = (2x-1)e^{-x+1}$ definie sur $\\mathbb{R}$."),
    t("1. Limites en $\\pm \\infty$. (1 pt)"),
    t("2. Montrer que $f'(x) = (3-2x)e^{-x+1}$. Tableau de variation. (2 pts)"),
    t("3. Point d'inflexion. (1 pt)"),
    t("4. Tracer la courbe. (1 pt)"),
    t("5. Calculer $\\int_0^1 f(x)dx$. (2 pts)"),
  ],

  2020: [
    main("Epreuve de mathematiques du Baccalaureat D 2020"),
    sec("EXERCICE 1", "5 points"),
    t("1. Resoudre dans $\\mathbb{R}$: $\\ln(x^2 - 4) = \\ln(x+2) + \\ln 3$. (1,5 pts)"),
    t("2. Resoudre : $e^{2x} + e^x - 6 = 0$. (1,5 pts)"),
    t("3. Montrer que pour tout $x > 0$, $\\ln x \\leq x - 1$. (2 pts)"),
    sec("EXERCICE 2", "4 points"),
    t("Plan rapporte a un repere orthonorme. $A(2;3)$, $B(-1;1)$, $C(4;-1)$."),
    t("1. Montrer que le triangle $ABC$ est isocele. (1 pt)"),
    t("2. Determiner l'equation du cercle circonscrit. (1,5 pts)"),
    t("3. Equation de la tangente au cercle au point $A$. (1,5 pts)"),
    sec("EXERCICE 3", "4 points"),
    t("Suite $(U_n)$: $U_0 = 1$, $U_{n+1} = \\frac{U_n}{2} + \\frac{1}{U_n}$."),
    t("1. Montrer que $U_n > 0$ pour tout $n$. (0,5 pt)"),
    t("2. Montrer que $U_n \\geq \\sqrt{2}$ pour tout $n \\geq 1$. (1,5 pts)"),
    t("3. Montrer que $(U_n)$ est decroissante a partir du rang 1. (1 pt)"),
    t("4. En deduire que $(U_n)$ converge et calculer sa limite. (1 pt)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = \\frac{x^2 - x + 1}{x - 1}$ definie sur $\\mathbb{R} \\setminus \\{1\\}$."),
    t("1. Montrer que $f(x) = x + \\frac{1}{x-1}$. (1 pt)"),
    t("2. Limites, asymptotes. (1 pt)"),
    t("3. Montrer que la droite $y = x$ est asymptote oblique. Etudier la position de la courbe par rapport a cette asymptote. (1,5 pts)"),
    t("4. Variations et extremums. (1,5 pts)"),
    t("5. Tracer la courbe. (1 pt)"),
    t("6. Determiner les tangentes a la courbe paralleles a la droite $y = x$. (1 pt)"),
  ],

  2019: [
    main("Epreuve de mathematiques du Baccalaureat D 2019"),
    sec("EXERCICE 1", "5 points"),
    t("Soit $f(x) = x^3 - 6x^2 + 9x - 4$."),
    t("1. Verifier que $f(1) = 0$ et factoriser $f(x)$. (1,5 pts)"),
    t("2. Resoudre $f(x) = 0$ et $f(x) \\geq 0$. (1 pt)"),
    t("3. Etudier les variations de $f$. (1,5 pts)"),
    t("4. Tracer la courbe. (1 pt)"),
    sec("EXERCICE 2", "4 points"),
    t("Suite geometrique $(U_n)$ de raison $q = \\frac{1}{2}$ et $U_0 = 8$."),
    t("1. Exprimer $U_n$ en fonction de $n$. (0,5 pt)"),
    t("2. Calculer $S_n = \\sum_{k=0}^{n} U_k$. (1 pt)"),
    t("3. Determiner $n$ tel que $S_n > 15$. (1 pt)"),
    t("4. Calculer $\\lim_{n \\to +\\infty} S_n$. (0,5 pt)"),
    t("5. On pose $T_n = \\sum_{k=0}^{n} \\ln(U_k)$. Exprimer $T_n$ en fonction de $n$. (1 pt)"),
    sec("EXERCICE 3", "4 points"),
    t("Nombres complexes. $z_A = 1+2i$, $z_B = 3-i$, $z_C = -1+i$."),
    t("1. Placer $A$, $B$, $C$. (0,5 pt)"),
    t("2. Calculer $\\frac{z_C - z_A}{z_B - z_A}$. En deduire la nature du triangle $ABC$. (2 pts)"),
    t("3. Determiner l'affixe du point $D$ tel que $ABCD$ soit un parallelogramme. (1,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = xe^{1-x}$ sur $\\mathbb{R}$."),
    t("1. Limites en $\\pm \\infty$. (1 pt)"),
    t("2. $f'(x) = (1-x)e^{1-x}$. Variations. (1,5 pts)"),
    t("3. Montrer que $f$ admet un maximum egal a 1. (0,5 pt)"),
    t("4. Equation de la tangente en $x = 0$. (1 pt)"),
    t("5. Tracer la courbe. (1 pt)"),
    t("6. Calculer $\\int_0^1 f(x)dx$. (2 pts)"),
  ],

  2018: [
    main("Epreuve de mathematiques du Baccalaureat D 2018"),
    sec("EXERCICE 1", "4 points"),
    t("Resoudre dans $\\mathbb{R}$ :"),
    t("1. $e^{3x-1} = e^{x+5}$. (0,5 pt)"),
    t("2. $\\ln(2x-1) \\leq 0$. (1 pt)"),
    t("3. $(\\ln x)^2 - 5\\ln x + 6 = 0$. (1,5 pts)"),
    t("4. $2^x = 5$ (donner la valeur exacte). (1 pt)"),
    sec("EXERCICE 2", "5 points"),
    t("$A(1;3)$, $B(-2;1)$, $C(4;-1)$ dans un repere orthonorme."),
    t("1. Calculer $AB$, $AC$ et $BC$. (1 pt)"),
    t("2. Montrer que le triangle est rectangle en $A$. (1 pt)"),
    t("3. Equation du cercle circonscrit. (1 pt)"),
    t("4. Equation de la hauteur issue de $A$. (1 pt)"),
    t("5. Coordonnees de l'orthocentre $H$. (1 pt)"),
    sec("EXERCICE 3", "4 points"),
    t("$(U_n)$: $U_1 = 1$, $U_{n+1} = 3U_n + 2$."),
    t("1. Calculer $U_2$, $U_3$, $U_4$. (0,5 pt)"),
    t("2. Soit $V_n = U_n + 1$. Montrer que $(V_n)$ est geometrique. (1 pt)"),
    t("3. Exprimer $U_n$ en fonction de $n$. (1 pt)"),
    t("4. Calculer $S_n = \\sum_{k=1}^{n} U_k$. (1,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = (x+1)e^{-x}$ sur $\\mathbb{R}$."),
    t("1. Limites. (1 pt)"),
    t("2. $f'(x) = -xe^{-x}$. Variations. (1,5 pts)"),
    t("3. Point d'inflexion. (1 pt)"),
    t("4. Tangente a l'origine. (0,5 pt)"),
    t("5. Courbe. (1 pt)"),
    t("6. Aire entre la courbe, l'axe $Ox$ et les droites $x = 0$, $x = 2$. (2 pts)"),
  ],

  2017: [
    main("Epreuve de mathematiques du Baccalaureat D 2017"),
    sec("EXERCICE 1", "5 points"),
    t("Resoudre dans $\\mathbb{R}$ :"),
    t("1. $e^{2x} - 5e^x + 6 = 0$. (1,5 pts)"),
    t("2. $\\ln(x+3) + \\ln(x-1) = \\ln 5$. (1,5 pts)"),
    t("3. $|2x - 3| \\leq 5$. (1 pt)"),
    t("4. Simplifier $A = \\ln(e^3) + e^{\\ln 5} - \\ln\\frac{1}{e^2}$. (1 pt)"),
    sec("EXERCICE 2", "4 points"),
    t("Suite $(U_n)$: $U_0 = 0$, $U_{n+1} = \\frac{1}{3}U_n + 2$."),
    t("1. Calculer $U_1$, $U_2$, $U_3$. (0,5 pt)"),
    t("2. Montrer que $(V_n) = U_n - 3$ est geometrique de raison $\\frac{1}{3}$. (1 pt)"),
    t("3. Exprimer $U_n$ en fonction de $n$. (1 pt)"),
    t("4. Limite de $(U_n)$. (0,5 pt)"),
    t("5. Calculer $S_n = \\sum_{k=0}^{n} U_k$. (1 pt)"),
    sec("EXERCICE 3", "4 points"),
    t("Probabilites. Un lot de 100 pieces dont 10 defectueuses."),
    t("1. On tire une piece. $P$(defectueuse). (0,5 pt)"),
    t("2. On tire 5 pieces avec remise. $P$(au moins une defectueuse). (1,5 pts)"),
    t("3. On tire 3 pieces sans remise. $P$(exactement 1 defectueuse). (2 pts)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = x^2 \\ln x$ sur $]0; +\\infty[$."),
    t("1. $\\lim_{x \\to 0^+} f(x) = 0$. (1 pt)"),
    t("2. $f'(x) = x(2\\ln x + 1)$. Variations. (2 pts)"),
    t("3. Tableau de variation et courbe. (1,5 pts)"),
    t("4. Equation de la tangente en $x = 1$. (0,5 pt)"),
    t("5. $\\int_1^e x\\ln x \\, dx$. (2 pts)"),
  ],

  2016: [
    main("Epreuve de mathematiques du Baccalaureat D 2016"),
    sec("EXERCICE 1", "4 points"),
    t("1. Resoudre $3^{x+1} = 27$. (0,5 pt)"),
    t("2. Resoudre $\\ln(x-1) + \\ln(x+3) = \\ln 5$. (1,5 pts)"),
    t("3. Simplifier $e^{2\\ln 3 - \\ln 9 + 1}$. (1 pt)"),
    t("4. Resoudre $e^{x^2-1} < 1$. (1 pt)"),
    sec("EXERCICE 2", "5 points"),
    t("$(O, \\vec{i}, \\vec{j})$ repere orthonorme. $A(1;2)$, $B(3;-2)$, $C(-1;0)$."),
    t("1. Nature du triangle $ABC$. (1,5 pts)"),
    t("2. Coordonnees du centre de gravite $G$. (0,5 pt)"),
    t("3. Equation du cercle de centre $G$ et de rayon 2. (1 pt)"),
    t("4. Determiner les points d'intersection du cercle avec l'axe des abscisses. (1 pt)"),
    t("5. Equation de la droite $(AB)$. (1 pt)"),
    sec("EXERCICE 3", "4 points"),
    t("Denombrement et probabilites. On dispose de 8 livres differents."),
    t("1. De combien de manieres peut-on ranger 5 livres sur une etagere ? (1 pt)"),
    t("2. De combien de manieres peut-on choisir 3 livres ? (0,5 pt)"),
    t("3. Parmi les 8 livres, 3 sont de maths et 5 de physique. On choisit 4 livres. Probabilite d'avoir exactement 2 livres de maths. (2,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = \\frac{\\ln x}{x^2}$ sur $]0; +\\infty[$."),
    t("1. Limites en $0^+$ et $+\\infty$. (1 pt)"),
    t("2. $f'(x) = \\frac{1 - 2\\ln x}{x^3}$. Variations. (2 pts)"),
    t("3. Maximum de $f$. (0,5 pt)"),
    t("4. Courbe. (1 pt)"),
    t("5. $\\int_1^e f(x)dx$. (2,5 pts)"),
  ],

  2015: [
    main("Epreuve de mathematiques du Baccalaureat D 2015"),
    sec("EXERCICE 1", "5 points"),
    t("$f(x) = x^4 - 5x^2 + 4$."),
    t("1. Verifier que $f(1) = 0$ et $f(2) = 0$. (0,5 pt)"),
    t("2. Factoriser $f(x)$. (1,5 pts)"),
    t("3. Resoudre $f(x) = 0$ et $f(x) > 0$. (1 pt)"),
    t("4. Variations et courbe de $f$. (2 pts)"),
    sec("EXERCICE 2", "4 points"),
    t("$(U_n)$: $U_0 = 5$, $U_{n+1} = 2U_n - 3$."),
    t("1. Calculer $U_1$, $U_2$, $U_3$. (0,5 pt)"),
    t("2. $(V_n) = U_n - 3$ geometrique. (1 pt)"),
    t("3. $U_n$ en fonction de $n$. Limite. (1,5 pts)"),
    t("4. $S_n = \\sum_{k=0}^{n} U_k$. (1 pt)"),
    sec("EXERCICE 3", "4 points"),
    t("Probabilites conditionnelles. Usine : 40% machine A, 60% machine B. Defaut : 5% pour A, 3% pour B."),
    t("1. Arbre pondere. (0,5 pt)"),
    t("2. Probabilite qu'une piece soit defectueuse. (1 pt)"),
    t("3. Sachant qu'une piece est defectueuse, probabilite qu'elle vienne de A. (1,5 pts)"),
    t("4. On choisit 10 pieces de A. Probabilite qu'au moins une soit defectueuse. (1 pt)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = (2-x)e^x$ sur $\\mathbb{R}$."),
    t("1. Limites. (1 pt)"),
    t("2. $f'(x) = (1-x)e^x$. Variations. (1,5 pts)"),
    t("3. Tangente au point $A(0; 2)$. (1 pt)"),
    t("4. Courbe. (1 pt)"),
    t("5. $\\int_0^2 f(x)dx$. (2,5 pts)"),
  ],

  2014: [
    main("Epreuve de mathematiques du Baccalaureat D 2014"),
    sec("EXERCICE 1", "4 points"),
    t("1. Resoudre dans $\\mathbb{R}$: $e^{2x} - 4e^x + 3 = 0$. (1,5 pts)"),
    t("2. Resoudre : $\\ln(2x+1) > \\ln(x+3)$. (1 pt)"),
    t("3. Resoudre : $\\sqrt{x+2} = x$. (1,5 pts)"),
    sec("EXERCICE 2", "5 points"),
    t("$(U_n)$: $U_0 = 1$, $U_{n+1} = \\frac{U_n + 2}{U_n + 1}$ sur $\\mathbb{N}$."),
    t("1. Montrer que $U_n > 0$ pour tout $n$. (0,5 pt)"),
    t("2. Montrer par recurrence que $U_n \\leq 2$ pour tout $n$. (1,5 pts)"),
    t("3. Montrer que $(U_n)$ est croissante. (1 pt)"),
    t("4. En deduire que $(U_n)$ converge et calculer sa limite. (2 pts)"),
    sec("EXERCICE 3", "4 points"),
    t("Espace. $ABCDEFGH$ cube de cote $a$. $I$ milieu de $[AB]$, $J$ milieu de $[BC]$."),
    t("1. Calculer $\\overrightarrow{IJ}$, $\\overrightarrow{IE}$. (1 pt)"),
    t("2. Calculer $IJ$, $IE$ et $\\overrightarrow{IJ} \\cdot \\overrightarrow{IE}$. (1,5 pts)"),
    t("3. Angle $\\widehat{(IJ, IE)}$. (1,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = (x-2)e^{x-1}$ sur $\\mathbb{R}$."),
    t("1. Limites. Asymptote. (1 pt)"),
    t("2. $f'(x)$ et variations. (2 pts)"),
    t("3. Tangente en $x = 2$. (1 pt)"),
    t("4. Courbe. (1 pt)"),
    t("5. $\\int_1^2 f(x)dx$. (2 pts)"),
  ],

  2013: [
    main("Epreuve de mathematiques du Baccalaureat D 2013"),
    sec("EXERCICE 1", "5 points"),
    t("Soit $f(x) = x^3 - 3x + 2$."),
    t("1. Etudier les variations de $f$. (1,5 pts)"),
    t("2. Resoudre $f(x) = 0$. (1 pt)"),
    t("3. Tableau de signes de $f(x)$. (1 pt)"),
    t("4. Courbe de $f$. (1,5 pts)"),
    sec("EXERCICE 2", "4 points"),
    t("Plan rapporte $(O, \\vec{i}, \\vec{j})$. $C$: $x^2+y^2-2x+4y-4=0$."),
    t("1. Centre et rayon de $C$. (1 pt)"),
    t("2. Position de $A(3;1)$ par rapport a $C$. (1 pt)"),
    t("3. Tangentes a $C$ passant par $A$. (2 pts)"),
    sec("EXERCICE 3", "4 points"),
    t("Probabilites. Urne: 4 rouges, 3 blanches, 2 noires."),
    t("1. On tire 2 boules. $P$(meme couleur). (2 pts)"),
    t("2. On tire 3 boules. $P$(au moins une rouge). (2 pts)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = \\frac{e^x}{e^x + 1}$ sur $\\mathbb{R}$."),
    t("1. Limites en $\\pm\\infty$. (1 pt)"),
    t("2. Montrer que $f'(x) = \\frac{e^x}{(e^x+1)^2}$. Variations. (1,5 pts)"),
    t("3. Montrer que le point $I(0; \\frac{1}{2})$ est centre de symetrie de la courbe. (1,5 pts)"),
    t("4. Courbe. (1 pt)"),
    t("5. $\\int_0^1 f(x)dx$. (Indication: $f(x) = 1 - \\frac{1}{e^x+1}$.) (2 pts)"),
  ],

  2012: [
    main("Epreuve de mathematiques du Baccalaureat D 2012"),
    sec("EXERCICE 1", "4 points"),
    t("1. Resoudre $2\\ln x - \\ln(x-1) = 0$. (1,5 pts)"),
    t("2. Resoudre $e^{2x} - 3e^x - 4 = 0$. (1,5 pts)"),
    t("3. Simplifier $\\ln(e^2 \\times \\sqrt{e})$. (1 pt)"),
    sec("EXERCICE 2", "5 points"),
    t("$(U_n)$: $U_0 = 3$ et $U_{n+1} = \\frac{1}{4}U_n + \\frac{3}{2}$."),
    t("1. $(V_n) = U_n - 2$. Montrer que $(V_n)$ est geometrique. (1,5 pts)"),
    t("2. $V_n$ puis $U_n$ en fonction de $n$. (1 pt)"),
    t("3. Limite de $(U_n)$. (0,5 pt)"),
    t("4. $S_n = \\sum_{k=0}^{n} U_k$ en fonction de $n$. (2 pts)"),
    sec("EXERCICE 3", "4 points"),
    t("Geometrie analytique. $A(1;2)$, $B(5;4)$, $C(3;-2)$."),
    t("1. Equation de $(AB)$. (1 pt)"),
    t("2. Equation de la perpendiculaire a $(AB)$ passant par $C$. (1 pt)"),
    t("3. Coordonnees du pied de la hauteur. (1 pt)"),
    t("4. Distance de $C$ a $(AB)$. (1 pt)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = \\frac{x^2+1}{x}$ sur $]0;+\\infty[$."),
    t("1. $f(x) = x + \\frac{1}{x}$. (0,5 pt)"),
    t("2. Limites, asymptotes. (1 pt)"),
    t("3. $f'(x) = 1 - \\frac{1}{x^2}$. Variations. (1,5 pts)"),
    t("4. Minimum. (0,5 pt)"),
    t("5. Courbe. (1,5 pts)"),
    t("6. Aire entre la courbe, l'axe des abscisses et les droites $x=1$, $x=2$. (2 pts)"),
  ],

  2011: [
    main("Epreuve de mathematiques du Baccalaureat D 2011"),
    sec("EXERCICE 1", "5 points"),
    t("$f(x) = x^3 - 6x^2 + 11x - 6$."),
    t("1. $f(1) = 0$. Factoriser $f(x)$. (1,5 pts)"),
    t("2. Resoudre $f(x) = 0$, $f(x) > 0$, $f(x) < 0$. (1 pt)"),
    t("3. Etudier les variations de $f$ et tracer sa courbe. (2,5 pts)"),
    sec("EXERCICE 2", "4 points"),
    t("Suite definie par $U_0 = 4$, $U_{n+1} = \\frac{1}{2}U_n + 1$."),
    t("1. Conjecturer la limite. (0,5 pt)"),
    t("2. $V_n = U_n - 2$ geometrique. (1 pt)"),
    t("3. $U_n$ en fonction de $n$. Limite. (1,5 pts)"),
    t("4. $S_n$. (1 pt)"),
    sec("EXERCICE 3", "4 points"),
    t("Nombres complexes. $z_1 = 2 + i$, $z_2 = 1 - 3i$."),
    t("1. $z_1 + z_2$, $z_1 \\times z_2$, $\\frac{z_1}{z_2}$. (1,5 pts)"),
    t("2. Module et argument de $z_1$. (1 pt)"),
    t("3. Forme trigonometrique de $z_1$. (1,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = (x-1)\\ln x$ sur $]0;+\\infty[$."),
    t("1. $\\lim_{x \\to 0^+} f(x)$. (1 pt)"),
    t("2. $f'(x) = \\ln x + 1 - \\frac{1}{x}$. Variations. (2 pts)"),
    t("3. Montrer que $f$ admet un minimum. (1 pt)"),
    t("4. Courbe. (1 pt)"),
    t("5. $\\int_1^e f(x)dx$. (2 pts)"),
  ],

  2010: [
    main("Epreuve de mathematiques du Baccalaureat D 2010"),
    sec("EXERCICE 1", "4 points"),
    t("1. Resoudre dans $\\mathbb{R}$: $4^x - 2^{x+1} = 0$. (1 pt)"),
    t("2. Resoudre : $\\ln x + \\ln(x+2) = \\ln 3$. (1,5 pts)"),
    t("3. Simplifier $A = \\frac{e^3 \\times e^{-2}}{(e^2)^3}$. (0,5 pt)"),
    t("4. Resoudre $x^2 e^x - 4e^x = 0$. (1 pt)"),
    sec("EXERCICE 2", "5 points"),
    t("$A(0;3)$, $B(4;1)$, $C(-2;-3)$ dans un repere orthonorme."),
    t("1. $AB$, $AC$, $BC$. Nature du triangle. (1,5 pts)"),
    t("2. Equation du cercle $(\\Gamma)$ de diametre $[BC]$. (1,5 pts)"),
    t("3. Montrer que $A \\in (\\Gamma)$. (1 pt)"),
    t("4. Equation de la tangente a $(\\Gamma)$ au point $A$. (1 pt)"),
    sec("EXERCICE 3", "4 points"),
    t("Probabilites. Boite: 5 vertes, 3 rouges, 2 blanches."),
    t("1. On tire 2 boules sans remise. $P$(2 vertes). (1 pt)"),
    t("2. $P$(1 verte et 1 rouge). (1 pt)"),
    t("3. On tire 3 boules. $P$(au moins 1 blanche). (2 pts)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = \\frac{x+1}{x}e^{-x}$ sur $]0;+\\infty[$."),
    t("1. Limites en $0^+$ et $+\\infty$. (1 pt)"),
    t("2. $f'(x)$ et variations. (2 pts)"),
    t("3. Courbe. (1,5 pts)"),
    t("4. $\\int_1^2 \\frac{1}{x}e^{-x}dx$. (2,5 pts)"),
  ],

  2009: [
    main("Epreuve de mathematiques du Baccalaureat D 2009"),
    sec("EXERCICE 1", "5 points"),
    t("Soit $f(x) = \\frac{x^2-1}{x^2+1}$."),
    t("1. Ensemble de definition, limites. (1 pt)"),
    t("2. Montrer que $f$ est paire. (0,5 pt)"),
    t("3. $f'(x) = \\frac{4x}{(x^2+1)^2}$. Variations. (2 pts)"),
    t("4. Courbe. (1,5 pts)"),
    sec("EXERCICE 2", "4 points"),
    t("$(U_n)$: $U_0 = 0$, $U_{n+1} = 2U_n + 3$."),
    t("1. $U_1$, $U_2$, $U_3$. (0,5 pt)"),
    t("2. $V_n = U_n + 3$ geometrique. (1 pt)"),
    t("3. $U_n$ en fonction de $n$. (1 pt)"),
    t("4. $S_n = \\sum_{k=0}^n U_k$. (1,5 pts)"),
    sec("EXERCICE 3", "4 points"),
    t("Plan. Cercle $C$: $(x-2)^2 + (y+1)^2 = 25$."),
    t("1. Centre et rayon. (0,5 pt)"),
    t("2. Position de $A(5;3)$ et $B(-1;-5)$ par rapport a $C$. (1 pt)"),
    t("3. Equation de la droite $(AB)$. (1 pt)"),
    t("4. Points d'intersection de $(AB)$ et $C$. (1,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("$g(x) = \\frac{e^x}{x}$ sur $]0;+\\infty[$."),
    t("1. Limites en $0^+$ et $+\\infty$. (1 pt)"),
    t("2. $g'(x)$. Variations. (2 pts)"),
    t("3. Minimum de $g$. (0,5 pt)"),
    t("4. Courbe. (1,5 pts)"),
    t("5. $\\int_1^2 g(x)dx$. (2 pts)"),
  ],

  2008: [
    main("Epreuve de mathematiques du Baccalaureat D 2008"),
    sec("EXERCICE 1", "4 points"),
    t("1. $e^{x+1} = 3$. (0,5 pt)"),
    t("2. $\\ln(3x-2) = 1$. (0,5 pt)"),
    t("3. $e^{2x} - e^x - 2 = 0$. (1,5 pts)"),
    t("4. $\\ln x + \\ln(x-2) \\leq \\ln 3$. (1,5 pts)"),
    sec("EXERCICE 2", "5 points"),
    t("$A(1;-1)$, $B(3;3)$, $C(-1;5)$. Montrer que $ABC$ est isocele rectangle. (2 pts)"),
    t("Equation du cercle. (1,5 pts)"),
    t("$D$ tel que $ABCD$ est un carre. Coordonnees de $D$. (1,5 pts)"),
    sec("EXERCICE 3", "4 points"),
    t("Suite $(U_n)$: $U_0 = 1$, $U_{n+1} = \\sqrt{U_n + 6}$."),
    t("1. $0 \\leq U_n \\leq 3$ par recurrence. (1,5 pts)"),
    t("2. $(U_n)$ croissante. (1 pt)"),
    t("3. Convergence et limite. (1,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = xe^{-x^2}$ sur $\\mathbb{R}$."),
    t("1. Limites. Montrer que $f$ est impaire. (1 pt)"),
    t("2. $f'(x) = (1-2x^2)e^{-x^2}$. Variations. (2 pts)"),
    t("3. Points d'inflexion. (1 pt)"),
    t("4. Courbe. (1 pt)"),
    t("5. Primitive de $f$. Aire. (2 pts)"),
  ],

  2007: [
    main("Epreuve de mathematiques du Baccalaureat D 2007"),
    sec("EXERCICE 1", "5 points"),
    t("$f(x) = x - 2 + \\frac{4}{x+1}$ sur $]-1;+\\infty[$."),
    t("1. Limites. Asymptote oblique $y = x-2$. (1,5 pts)"),
    t("2. $f'(x)$. Variations. (1,5 pts)"),
    t("3. Courbe. (1 pt)"),
    t("4. $f(x) = 0$. (1 pt)"),
    sec("EXERCICE 2", "4 points"),
    t("Nombres complexes. $z = 1 + i\\sqrt{3}$."),
    t("1. Module et argument de $z$. (1 pt)"),
    t("2. Ecriture trigonometrique de $z$. (0,5 pt)"),
    t("3. Calculer $z^6$. (1 pt)"),
    t("4. Resoudre $Z^2 = z$. (1,5 pts)"),
    sec("EXERCICE 3", "4 points"),
    t("Denombrement. 6 garcons et 4 filles."),
    t("1. Nombre de comites de 4 personnes. (0,5 pt)"),
    t("2. Nombre de comites avec exactement 2 garcons. (1 pt)"),
    t("3. Probabilite qu'un comite de 4 ait au moins une fille. (1,5 pts)"),
    t("4. Nombre d'arrangements de 3 parmi 10. (1 pt)"),
    sec("PROBLEME", "7 points"),
    t("$g(x) = x^2 e^{-x}$ sur $\\mathbb{R}$."),
    t("1. Limites. (1 pt)"),
    t("2. $g'(x) = x(2-x)e^{-x}$. Variations. (2 pts)"),
    t("3. Courbe. (1,5 pts)"),
    t("4. $\\int_0^1 g(x)dx$ par parties. (2,5 pts)"),
  ],

  2006: [
    main("Epreuve de mathematiques du Baccalaureat D 2006"),
    sec("EXERCICE 1", "4 points"),
    t("1. Resoudre $2e^{2x} - 7e^x + 3 = 0$. (1,5 pts)"),
    t("2. Resoudre $\\ln|x| = 2$. (1 pt)"),
    t("3. Resoudre $x\\ln x - x = 0$ sur $]0;+\\infty[$. (1,5 pts)"),
    sec("EXERCICE 2", "5 points"),
    t("Suite: $U_1 = 2$, $U_{n+1} = 5 - \\frac{6}{U_n}$."),
    t("1. $U_2$, $U_3$. (0,5 pt)"),
    t("2. Montrer que $2 \\leq U_n \\leq 3$ par recurrence. (1,5 pts)"),
    t("3. $(U_n)$ croissante. (1 pt)"),
    t("4. $V_n = \\frac{U_n - 3}{U_n - 2}$ geometrique. (1 pt)"),
    t("5. $U_n$ en fonction de $n$. Limite. (1 pt)"),
    sec("EXERCICE 3", "4 points"),
    t("Plan. $A(0;2)$, $B(4;0)$, $C(2;4)$."),
    t("1. Equations de $(AB)$ et $(AC)$. (1 pt)"),
    t("2. Equation du cercle de centre $C$ passant par $A$. (1 pt)"),
    t("3. Intersection du cercle avec l'axe $Ox$. (2 pts)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = \\ln(x^2+1)$ sur $\\mathbb{R}$."),
    t("1. Parite de $f$. (0,5 pt)"),
    t("2. $f'(x) = \\frac{2x}{x^2+1}$. Variations. (1,5 pts)"),
    t("3. Tangente a l'origine. (1 pt)"),
    t("4. Courbe. (1,5 pts)"),
    t("5. $\\int_0^1 f(x)dx$. (2,5 pts)"),
  ],

  2005: [
    main("Epreuve de mathematiques du Baccalaureat D 2005"),
    sec("EXERCICE 1", "5 points"),
    t("$f(x) = \\frac{x^2 + x + 1}{x + 1}$ sur $\\mathbb{R} \\setminus \\{-1\\}$."),
    t("1. $f(x) = x + \\frac{1}{x+1}$. (1 pt)"),
    t("2. Limites et asymptotes. (1,5 pts)"),
    t("3. Variations. Courbe. (2,5 pts)"),
    sec("EXERCICE 2", "4 points"),
    t("Probabilites. 3 urnes. Urne 1: 2R, 3B. Urne 2: 4R, 1B. Urne 3: 3R, 3B."),
    t("1. On choisit une urne au hasard puis on tire une boule. $P$(Rouge). (2 pts)"),
    t("2. Sachant que la boule est rouge, probabilite qu'elle vienne de l'urne 2. (2 pts)"),
    sec("EXERCICE 3", "4 points"),
    t("$(U_n)$: $U_0 = 0$, $U_{n+1} = 2U_n + 1$."),
    t("1. $U_1$, $U_2$, $U_3$. (0,5 pt)"),
    t("2. $V_n = U_n + 1$ geometrique. (1 pt)"),
    t("3. $U_n$ en fonction de $n$. (1 pt)"),
    t("4. $S_n$. Limite. (1,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("$g(x) = (1-x)e^x$ sur $\\mathbb{R}$."),
    t("1. Limites. (1 pt)"),
    t("2. $g'(x) = -xe^x$. Variations. (1,5 pts)"),
    t("3. Courbe. (1,5 pts)"),
    t("4. $\\int_0^1 g(x)dx$. (2 pts)"),
    t("5. Aire. (1 pt)"),
  ],

  2004: [
    main("Epreuve de mathematiques du Baccalaureat D 2004"),
    sec("EXERCICE 1", "5 points"),
    t("$f(x) = x^3 - 3x^2 + 4$."),
    t("1. $f(-1) = 0$. Factoriser. (1,5 pts)"),
    t("2. Signe de $f(x)$. (1 pt)"),
    t("3. Variations et courbe. (2,5 pts)"),
    sec("EXERCICE 2", "4 points"),
    t("Plan. $A(2;3)$, $B(-1;-1)$."),
    t("1. Equation de $(AB)$. (1 pt)"),
    t("2. Equation de la mediatrice de $[AB]$. (1 pt)"),
    t("3. Cercle de diametre $[AB]$. Equation. (1 pt)"),
    t("4. Tangente au cercle en $A$. (1 pt)"),
    sec("EXERCICE 3", "4 points"),
    t("Combinatoire. Classe de 12 garcons et 8 filles."),
    t("1. Nombre de delegations de 5 eleves. (0,5 pt)"),
    t("2. Nombre de delegations avec au moins 2 filles. (2 pts)"),
    t("3. Probabilite qu'une delegation de 5 ait exactement 3 garcons. (1,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = x - 1 + 2e^{-x}$ sur $\\mathbb{R}$."),
    t("1. Limites. Asymptote oblique $y = x - 1$. (1,5 pts)"),
    t("2. $f'(x) = 1 - 2e^{-x}$. Variations. (1,5 pts)"),
    t("3. Courbe. (1,5 pts)"),
    t("4. $\\int_0^{\\ln 2} f(x)dx$. (2,5 pts)"),
  ],

  2003: [
    main("Epreuve de mathematiques du Baccalaureat D 2003"),
    sec("EXERCICE 1", "4 points"),
    t("1. Resoudre $\\ln(x+1) + \\ln(x-1) = \\ln 8$. (1,5 pts)"),
    t("2. Resoudre $e^{2x} + e^x - 6 = 0$. (1,5 pts)"),
    t("3. Simplifier $\\ln(\\sqrt{e} \\times e^3) - 2\\ln e$. (1 pt)"),
    sec("EXERCICE 2", "5 points"),
    t("Plan orthonorme. $A(-1;3)$, $B(5;1)$, $C(1;-3)$."),
    t("1. Milieu $I$ de $[BC]$. Coordonnees. (0,5 pt)"),
    t("2. Nature du triangle $ABC$. (1,5 pts)"),
    t("3. Cercle circoncrit. Equation. (1,5 pts)"),
    t("4. $D$ symetrique de $A$ par rapport a $I$. Nature de $ABDC$. (1,5 pts)"),
    sec("EXERCICE 3", "4 points"),
    t("$(U_n)$: $U_0 = 1$, $U_{n+1} = 3U_n - 4$."),
    t("1. $U_1$, $U_2$, $U_3$. (0,5 pt)"),
    t("2. $V_n = U_n - 2$ geometrique de raison 3. (1 pt)"),
    t("3. $U_n$ en fonction de $n$. Limite. (1,5 pts)"),
    t("4. $S_n$. (1 pt)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = xe^{-x}$ sur $\\mathbb{R}$."),
    t("1. Limites. (1 pt)"),
    t("2. $f'(x) = (1-x)e^{-x}$. Variations. (1,5 pts)"),
    t("3. Maximum. (0,5 pt)"),
    t("4. Tangentes en $x=0$ et $x=2$. (1 pt)"),
    t("5. Courbe. (1 pt)"),
    t("6. $\\int_0^2 f(x)dx$. (2 pts)"),
  ],

  2002: [
    main("Epreuve de mathematiques du Baccalaureat D 2002"),
    sec("EXERCICE 1", "5 points"),
    t("$f(x) = \\frac{x^2 - 4}{x - 1}$ sur $\\mathbb{R} \\setminus \\{1\\}$."),
    t("1. Limites. Asymptote verticale. (1 pt)"),
    t("2. $f(x) = x + 1 - \\frac{3}{x-1}$. Asymptote oblique. (1,5 pts)"),
    t("3. Variations. (1,5 pts)"),
    t("4. Courbe. (1 pt)"),
    sec("EXERCICE 2", "4 points"),
    t("Probabilites. De truque: $P(6) = \\frac{1}{3}$, les 5 autres faces equiprobables."),
    t("1. $P$ de chaque face. (1 pt)"),
    t("2. On lance 2 fois. $P$(somme = 12). (1 pt)"),
    t("3. $P$(somme $\\geq$ 10). (2 pts)"),
    sec("EXERCICE 3", "4 points"),
    t("Suite: $U_0 = 1$, $U_{n+1} = \\frac{1}{2}(U_n + \\frac{3}{U_n})$."),
    t("1. $U_1$, $U_2$. (0,5 pt)"),
    t("2. Montrer que $U_n \\geq \\sqrt{3}$ pour $n \\geq 1$. (1,5 pts)"),
    t("3. $(U_n)$ decroissante pour $n \\geq 1$. Convergence. Limite. (2 pts)"),
    sec("PROBLEME", "7 points"),
    t("$g(x) = (x+2)e^{-x}$ sur $\\mathbb{R}$."),
    t("1. Limites. (1 pt)"),
    t("2. $g'(x) = (1-x)e^{-x}$ (erratum: $g'(x) = (-x-1)e^{-x}$... verifier). Variations. (2 pts)"),
    t("3. Tangente en $x = 0$. (1 pt)"),
    t("4. Courbe. (1 pt)"),
    t("5. $\\int_{-2}^0 g(x)dx$. (2 pts)"),
  ],

  2001: [
    main("Epreuve de mathematiques du Baccalaureat D 2001"),
    sec("EXERCICE 1", "5 points"),
    t("$f(x) = x^3 + 3x^2 - 9x - 27$."),
    t("1. $f(3) = 0$, $f(-3) = 0$. Factoriser $f(x)$. (2 pts)"),
    t("2. Signe de $f(x)$. (1 pt)"),
    t("3. Variations et courbe. (2 pts)"),
    sec("EXERCICE 2", "4 points"),
    t("Plan. Cercle: $x^2 + y^2 - 4x + 2y - 4 = 0$."),
    t("1. Centre et rayon. (1 pt)"),
    t("2. Droite $(D): y = x - 1$. Intersection avec le cercle. (2 pts)"),
    t("3. Tangente au cercle en $(0;2)$ (si ce point appartient au cercle). (1 pt)"),
    sec("EXERCICE 3", "4 points"),
    t("Probabilites. Lot de 20 pieces dont 4 defectueuses."),
    t("1. On tire 3 pieces. $P$(aucune defectueuse). (1,5 pts)"),
    t("2. $P$(au moins une defectueuse). (0,5 pt)"),
    t("3. $P$(exactement 2 defectueuses). (2 pts)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = x\\ln x - x + 1$ sur $]0;+\\infty[$."),
    t("1. $\\lim_{x \\to 0^+} f(x)$. (1 pt)"),
    t("2. $f'(x) = \\ln x$. Variations. (1,5 pts)"),
    t("3. Minimum de $f$. Montrer que $f(x) \\geq 0$. (1 pt)"),
    t("4. Courbe. (1,5 pts)"),
    t("5. $\\int_1^e x\\ln x \\, dx$. (2 pts)"),
  ],

  2000: [
    main("Epreuve de mathematiques du Baccalaureat D 2000"),
    sec("EXERCICE 1", "4 points"),
    t("1. Resoudre $x^4 - 5x^2 + 4 = 0$. (1,5 pts)"),
    t("2. Resoudre $\\ln(x-1) + \\ln(x+1) = \\ln 3$. (1,5 pts)"),
    t("3. Resoudre $e^{2x} = 3e^x$. (1 pt)"),
    sec("EXERCICE 2", "5 points"),
    t("Plan. $A(1;4)$, $B(5;2)$, $C(3;-2)$."),
    t("1. Nature du triangle $ABC$. (1,5 pts)"),
    t("2. Cercle de centre $A$ et rayon $AB$. Equation. (1 pt)"),
    t("3. Equation de $(BC)$. Points d'intersection avec le cercle. (2,5 pts)"),
    sec("EXERCICE 3", "4 points"),
    t("Suite: $U_1 = 1$, $U_{n+1} = 3U_n + 2$."),
    t("1. $U_2$, $U_3$, $U_4$. (0,5 pt)"),
    t("2. $V_n = U_n + 1$ geometrique. (1 pt)"),
    t("3. $U_n$ en fonction de $n$. (1 pt)"),
    t("4. $S_n = \\sum_{k=1}^{n} U_k$. Limite. (1,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("$f(x) = x^2 - 2\\ln x$ sur $]0;+\\infty[$."),
    t("1. Limites. (1 pt)"),
    t("2. $f'(x) = 2x - \\frac{2}{x} = \\frac{2(x^2-1)}{x}$. Variations. (2 pts)"),
    t("3. Minimum. (0,5 pt)"),
    t("4. Courbe. (1,5 pts)"),
    t("5. $\\int_1^e f(x)dx$. (2 pts)"),
  ],

  1999: [
    main("Epreuve de mathematiques du Baccalaureat D 1999"),
    sec("EXERCICE 1", "5 points"),
    t("$f(x) = \\frac{x^2+1}{x-1}$ sur $\\mathbb{R} \\setminus \\{1\\}$."),
    t("1. Montrer que $f(x) = x + 1 + \\frac{2}{x-1}$. (1 pt)"),
    t("2. Limites. Asymptote verticale et oblique. (1,5 pts)"),
    t("3. $f'(x)$. Variations. (1,5 pts)"),
    t("4. Courbe. (1 pt)"),
    sec("EXERCICE 2", "4 points"),
    t("Suite arithmetique $(U_n)$: $U_1 = 3$, raison $r = 2$."),
    t("1. $U_n$ en fonction de $n$. (0,5 pt)"),
    t("2. $S_n = \\sum_{k=1}^n U_k$. (1 pt)"),
    t("3. Soit $(V_n) = e^{U_n}$. Montrer que $(V_n)$ est geometrique. (1 pt)"),
    t("4. Produit $P_n = V_1 \\times V_2 \\times ... \\times V_n$. (1,5 pts)"),
    sec("EXERCICE 3", "4 points"),
    t("Combinatoire. Mot de 5 lettres avec les lettres A, B, C, D, E (sans repetition)."),
    t("1. Nombre de mots possibles. (0,5 pt)"),
    t("2. Nombre de mots commencant par une voyelle. (1 pt)"),
    t("3. Nombre de mots ou A et E ne sont pas voisins. (2,5 pts)"),
    sec("PROBLEME", "7 points"),
    t("$g(x) = (x^2 - 1)e^{-x}$ sur $\\mathbb{R}$."),
    t("1. Limites. (1 pt)"),
    t("2. $g'(x)$. Variations. (2 pts)"),
    t("3. Courbe. (1,5 pts)"),
    t("4. $\\int_0^1 (x^2-1)e^{-x}dx$. (2,5 pts)"),
  ],

};
