// ========================================
// Probatoire A Exam Data (1999-2026) - Ndolomath
// All content belongs to Ndolomath / Madame Mba
// ========================================

import type { ExamSection } from "./bac-d-data"

function ex(title: string, pts?: string, en?: string): ExamSection { return { type: "exercise", title, pts, en }; }
function sec(title: string, pts?: string, en?: string): ExamSection { return { type: "section", title, pts, en }; }
function subsec(title: string, pts?: string, en?: string): ExamSection { return { type: "subsection", title, pts, en }; }
function main(title: string, en?: string): ExamSection { return { type: "main", title, en }; }
function t(text: string, en?: string): ExamSection { return { type: "text", text, en }; }
function tbl(text: string, en?: string): ExamSection { return { type: "table", text, en }; }
function img(src: string, alt?: string): ExamSection { return { type: "image", src, text: alt }; }

export const PROBATOIRE_A_EXAMS: Record<number, ExamSection[]> = {

  // ===================== PROBATOIRE A 2025 =====================
  2025: [
    main("L'epreuve de mathematiques du PROBATOIRE A 2025", "Mathematics Exam - Probatoire A 2025"),

    sec("Partie A : Evaluation des ressources", "15 points", "Part A: Resource Assessment"),

    ex("Exercice 1 :", "04 points", "Exercise 1:"),
    t("1. Resoudre dans l'ensemble $\\mathbb{R}$, l'equation $x^2 + 2x - 48 = 0$ 2 pts",
      "1. Solve in $\\mathbb{R}$ the equation $x^2 + 2x - 48 = 0$ 2 pts"),
    t("2. 24 metres de tissu sont achetes et doivent etre equitablement partages aux eleves d'une classe de premiere litteraire pour leur devoir de couture. Apres l'achat de ce tissu, deux eleves ont ete admis dans la classe et chacun des eleves presents avant l'arrivee des deux nouveaux, a vu la longueur de son tissu, reduite d'un metre.",
      "2. 24 meters of fabric are purchased and must be equally shared among students of a first-year arts class for their sewing assignment. After the purchase, two students were admitted to the class and each student present before the arrival of the two new ones saw the length of their fabric reduced by one meter."),
    t("Soit $n$ l'effectif de cette classe avant l'admission des deux nouveaux eleves.",
      "Let $n$ be the number of students in this class before the admission of the two new students."),
    t("2.1 Exprimer a l'aide de $n$, la longueur de tissu de chaque eleve avant l'admission des deux eleves. 0,5 pt",
      "2.1 Express using $n$, the length of fabric for each student before the admission of the two students. 0.5 pt"),
    t("2.2 Exprimer a l'aide de $n$, la longueur de tissu a donner a chaque eleve apres l'admission des deux eleves. 0,5 pt",
      "2.2 Express using $n$, the length of fabric to give to each student after the admission of the two students. 0.5 pt"),
    t("2.3 Combien d'eleves cette classe comptait-elle avant la venue des deux nouveaux ? 1 pt",
      "2.3 How many students were in the class before the arrival of the two new ones? 1 pt"),

    ex("Exercice 2 :", "05,5 points", "Exercise 2:"),
    t("Une boite contient des aiguilles dont les longueurs, en millimetres, sont toutes inferieures a 20. La fiche des caracteristiques collees sur cette boite se presente de la maniere suivante :",
      "A box contains needles whose lengths, in millimeters, are all less than 20. The specification sheet on this box reads as follows:"),
    tbl("$\\begin{array}{|c|c|c|c|c|c|}\\hline \\text{Longueur en mm} & [0\\;;4[ & [4\\;;8[ & [8\\;;12[ & [12\\;;16[ & [16\\;;20[ \\\\ \\hline \\text{Effectifs} & 5 & 14 & 20 & 7 & 4 \\\\ \\hline \\end{array}$",
      "$\\begin{array}{|c|c|c|c|c|c|}\\hline \\text{Length in mm} & [0;4[ & [4;8[ & [8;12[ & [12;16[ & [16;20[ \\\\ \\hline \\text{Frequencies} & 5 & 14 & 20 & 7 & 4 \\\\ \\hline \\end{array}$"),
    t("1. Calculer la longueur moyenne d'une aiguille de cette boite. 2 pts",
      "1. Calculate the average length of a needle in this box. 2 pts"),
    t("2. a. Donner dans un meme tableau les effectifs cumules croissants et les effectifs cumules decroissants associes a cette serie statistique. 2,5 pts",
      "2. a. Give in a single table the cumulative increasing frequencies and cumulative decreasing frequencies associated with this statistical series. 2.5 pts"),
    t("b. En deduire l'intervalle median de cette serie. 1 pt",
      "b. Deduce the median interval of this series. 1 pt"),

    ex("Exercice 3 :", "05,5 points", "Exercise 3:"),
    t("La fonction $f$ est definie sur l'intervalle $[-2\\;;4]$ par $f(x)=x^2-2x-3$.",
      "The function $f$ is defined on the interval $[-2;4]$ by $f(x)=x^2-2x-3$."),
    t("1. Calculer pour tout reel $x$ de $[-2\\;;4]$, $f'(x)$ ou $f'$ est la fonction derivee de $f$. 1 pt",
      "1. Calculate for all real $x$ in $[-2;4]$, $f'(x)$ where $f'$ is the derivative of $f$. 1 pt"),
    t("2. Dresser le tableau des variations de $f$ sur $[-2\\;;4]$. 2 pts",
      "2. Draw the table of variations of $f$ on $[-2;4]$. 2 pts"),
    t("3. Dans un plan rapporte au repere orthonorme $(O,I,J)$, et ayant pris un centimetre comme l'unite sur chacun des axes de ce repere, faire des esquisses respectives sur un meme graphique, de la courbe de $f$ et celle de $-f$. 2,5 pts",
      "3. In a plane with orthonormal coordinate system $(O,I,J)$, taking one centimeter as the unit on each axis, sketch on the same graph the curves of $f$ and $-f$. 2.5 pts"),

    sec("PARTIE B : Evaluation des competences", "05 points", "PART B: Skills Assessment"),
    t("Situation : Trente des trente-deux eleves d'une classe de premiere litteraire doivent etre choisis pour aller au defile marquant la fete de la jeunesse dans une localite situee a 20 kilometres de l'etablissement. Tous les trente-deux eleves desirent participer a ce defile. Pour faire simple, le responsable a l'idee de constituer toutes les listes possibles de trente eleves de cette classe, d'introduire chacune d'elles dans une enveloppe non transparente pour un tirage au sort.",
      "Situation: Thirty of the thirty-two students in a first-year arts class must be chosen to go to the parade marking Youth Day in a locality 20 kilometers from the school. All thirty-two students want to participate. To keep it simple, the teacher decides to make all possible lists of thirty students, put each in an opaque envelope for a draw."),
    t("Ce responsable doit aussi prevoir comme rafraichissants, de l'eau et du jus, tous en bouteilles plastiques de meme contenance, pour un montant global de 12 600 francs. Un eleve choisira un seul des deux types de rafraichissants. Une bouteille de jus coute 500 francs, tandis qu'une bouteille d'eau coute 300 francs.",
      "The teacher must also provide refreshments: water and juice, all in plastic bottles of the same size, for a total of 12,600 francs. Each student will choose only one type. A bottle of juice costs 500 francs, while a bottle of water costs 300 francs."),
    t("L'heure limite d'arrivee des eleves a la place des fetes est prevue a 8 heures. Le car transportant ces eleves a partir de leur etablissement, part a 06 heures et 45 minutes, mais tombe en panne 30 minutes, apres avoir parcouru une distance de 15 km. Le chauffeur prend 30 minutes pour reparer la panne, puis reprend la route.",
      "The deadline for students to arrive at the festival grounds is 8 o'clock. The bus carrying the students from their school leaves at 6:45 AM, but breaks down 30 minutes later, having covered 15 km. The driver takes 30 minutes to fix the breakdown, then resumes driving."),

    subsec("Taches :", "", "Tasks:"),
    t("1. Quel est le nombre d'enveloppes a prevoir pour le tirage ? 1,5 pt",
      "1. How many envelopes are needed for the draw? 1.5 pt"),
    t("2. Combien faut-il prevoir des rafraichissants de chaque type ? 1,5 pt",
      "2. How many refreshments of each type should be planned? 1.5 pt"),
    t("3. A quelle vitesse moyenne minimale doit rouler le chauffeur pour que les eleves qu'il transporte arrivent a la place des fetes avant l'heure limite ? 1,5 pt",
      "3. What minimum average speed must the driver maintain for the students to arrive at the festival grounds before the deadline? 1.5 pt"),
    t("Presentation : 0,5 pt",
      "Presentation: 0.5 pt"),
  ],

  // ===================== PROBATOIRE A 2024 =====================
  2024: [
    main("L'epreuve de mathematiques du PROBATOIRE A 2024", "Mathematics Exam - Probatoire A 2024"),

    sec("Partie A : Evaluation des ressources", "13 points", "Part A: Resource Assessment"),

    ex("Exercice 1 :", "4 points", "Exercise 1:"),
    t("Lors des oraux d'un concours, un candidat doit tirer au hasard successivement et sans remise trois questions dans une urne opaque qui contient 3 questions d'anglais, 4 questions de francais et 5 questions de culture generale.",
      "During the oral exams of a competition, a candidate must randomly draw three questions successively without replacement from an opaque urn containing 3 English questions, 4 French questions and 5 general knowledge questions."),
    t("1. a) Combien de tirages possibles le candidat peut-il effectuer ? 1 pt",
      "1. a) How many possible draws can the candidate make? 1 pt"),
    t("b) Combien y a-t-il de tirages comportant des questions de la meme discipline ? 1 pt",
      "b) How many draws consist of questions from the same discipline? 1 pt"),
    t("Les 50 candidats a ce concours sont repartis selon leurs ages dans le tableau suivant :",
      "The 50 candidates for this competition are distributed by age in the following table:"),
    tbl("$\\begin{array}{|l|c|c|c|c|}\\hline \\text{Ages :} & [16\\;;18[ & [18\\;;20[ & [20\\;;22[ & [22\\;;24[ \\\\ \\hline \\text{Nombres de candidats} & 10 & 16 & 14 & 10 \\\\ \\hline \\end{array}$",
      "$\\begin{array}{|l|c|c|c|c|}\\hline \\text{Ages:} & [16;18[ & [18;20[ & [20;22[ & [22;24[ \\\\ \\hline \\text{Number of candidates} & 10 & 16 & 14 & 10 \\\\ \\hline \\end{array}$"),
    t("Pour chacune des questions suivantes, choisir la bonne reponse parmi les quatre proposees :",
      "For each of the following questions, choose the correct answer among the four proposed:"),
    t("2) La moyenne de cette serie statistique est egale a : 1 pt",
      "2) The mean of this statistical series is equal to: 1 pt"),
    t("a) 19 ; b) 19,96 ; c) 18,5 ; d) 19,5."),
    t("3) L'ecart-type de cette serie statistique est egal a : 1 pt",
      "3) The standard deviation of this statistical series is equal to: 1 pt"),
    t("a) 2,49 ; b) 2,409 ; c) 2,904 ; d) 2,049."),

    ex("Exercice 2 :", "3,5 points", "Exercise 2:"),
    t("On considere le polynome $Q$ a variable reelle $x$ defini par $Q(x)=-2x^2-9x+5$.",
      "Consider the polynomial $Q$ with real variable $x$ defined by $Q(x)=-2x^2-9x+5$."),
    t("1. Resoudre dans $\\mathbb{R}$ l'equation $Q(x)=0$. 1 pt",
      "1. Solve in $\\mathbb{R}$ the equation $Q(x)=0$. 1 pt"),
    t("2. Etudier le signe du polynome $Q(-x)$. 1 pt",
      "2. Study the sign of the polynomial $Q(-x)$. 1 pt"),
    t("3. En deduire dans $\\mathbb{R}$ l'ensemble solution de l'inequation $Q(x)\\le 0$. 1,5 pt",
      "3. Deduce in $\\mathbb{R}$ the solution set of the inequality $Q(x)\\le 0$. 1.5 pt"),

    ex("Exercice 3 :", "5,5 points", "Exercise 3:"),
    t("On considere la fonction numerique $f$ de la variable reelle $x$ definie dans $[-6\\;;-2[\\;\\cup\\;]-2\\;;4]$ par $f(x)=\\dfrac{x-1}{x+2}$. $(C)$ est la courbe representative de $f$ dans un repere orthonorme $(O;\\vec{i},\\vec{j})$.",
      "Consider the numerical function $f$ of real variable $x$ defined on $[-6;-2[\\;\\cup\\;]-2;4]$ by $f(x)=\\dfrac{x-1}{x+2}$. $(C)$ is the representative curve of $f$ in an orthonormal coordinate system $(O;\\vec{i},\\vec{j})$."),
    t("1. Calculer $\\displaystyle\\lim_{x\\to -2^-} f(x)$ et $\\displaystyle\\lim_{x\\to -2^+} f(x)$. 1 pt",
      "1. Calculate $\\displaystyle\\lim_{x\\to -2^-} f(x)$ and $\\displaystyle\\lim_{x\\to -2^+} f(x)$. 1 pt"),
    t("2. Deduire une equation cartesienne de l'asymptote verticale a la courbe $(C)$. 0,75 pt",
      "2. Deduce a Cartesian equation of the vertical asymptote of the curve $(C)$. 0.75 pt"),
    t("3. Montrer que pour tout reel $x$ distinct de $-2$, $f'(x)=\\dfrac{3}{(x+2)^2}$. 1 pt",
      "3. Show that for all real $x$ different from $-2$, $f'(x)=\\dfrac{3}{(x+2)^2}$. 1 pt"),
    t("4. Dresser le tableau de variations de $f$. 0,75 pt",
      "4. Draw the table of variations of $f$. 0.75 pt"),
    t("5. Ecrire une equation cartesienne de la tangente $(T)$ a $(C)$ au point d'abscisse $0$. 0,75 pt",
      "5. Write a Cartesian equation of the tangent $(T)$ to $(C)$ at the point with x-coordinate $0$. 0.75 pt"),
    t("6. Tracer dans le repere $(O;\\vec{i},\\vec{j})$ la droite $(T)$, la courbe $(C)$ et son asymptote. 1,5 pt",
      "6. Draw in the coordinate system $(O;\\vec{i},\\vec{j})$ the line $(T)$, the curve $(C)$ and its asymptote. 1.5 pt"),

    sec("Partie B : Evaluation des competences", "7 points", "Part B: Skills Assessment"),

    subsec("Situation :", "", "Situation:"),
    t("M. POKA a un terrain de forme rectangulaire de superficie 168 m$^2$ et de perimetre 52 m. Un des deux cotes le plus long est en bordure d'une route. Il voudrait securiser ce cote en y placant un grillage a raison de 5 000 FCFA le metre.",
      "Mr. POKA has a rectangular piece of land with an area of 168 m$^2$ and a perimeter of 52 m. One of the two longest sides borders a road. He wants to secure this side by placing a fence at a cost of 5,000 FCFA per meter."),
    t("Il souhaite offrir un gateau a ses eleves qui l'ont aide a securiser son terrain en guise de recompense. Une fois a la boulangerie, il constate que le gateau qui coutait 20 000 FCFA, coute actuellement 22 050 FCFA apres deux hausses successives de meme taux. M. POKA estime que ce montant est un peu couteux. Apres negociation, le responsable de la boulangerie lui demande de lui donner le montant correspondant a la premiere hausse qu'ils ignorent.",
      "He wants to offer a cake to his students who helped him secure his land as a reward. At the bakery, he finds that the cake which cost 20,000 FCFA now costs 22,050 FCFA after two successive increases at the same rate. Mr. POKA finds this amount a bit expensive. After negotiation, the bakery manager asks him to pay the amount corresponding to the first increase, which they don't know."),
    t("M. POKA, satisfait de l'aide que ses eleves lui ont apporte, decide en plus, de donner 8 000 FCFA a chacun d'eux pour leur permettre de participer aux olympiades. Ceux-ci decident de louer un car a raison de 96 000 FCFA. Mais au moment du depart, deux d'entre eux manquent a l'appel et chacun voit ses frais de transport augmenter de 4 000 FCFA. M. POKA voudrait avoir une idee du montant a debourser au moment du depart.",
      "Mr. POKA, satisfied with his students' help, also decides to give 8,000 FCFA to each of them to participate in the Olympiad. They decide to rent a bus for 96,000 FCFA. But at departure, two of them are missing and each sees their transport costs increase by 4,000 FCFA. Mr. POKA wants to know the amount to spend at departure."),

    subsec("Taches :", "", "Tasks:"),
    t("1- Quel est le montant debourse par M. POKA pour l'achat du grillage utilise pour securiser son terrain ? 2,25 pts",
      "1- What is the amount spent by Mr. POKA for purchasing the fence used to secure his land? 2.25 pts"),
    t("2- Quel est le montant que devrait debourser M. POKA pour l'achat du gateau apres la premiere hausse ? 2,25 pts",
      "2- What is the amount Mr. POKA should pay for the cake after the first increase? 2.25 pts"),
    t("3- Quel est le montant debourse par M. POKA pour la participation de ses eleves aux olympiades ? 2,25 pts",
      "3- What is the amount spent by Mr. POKA for his students' participation in the Olympiad? 2.25 pts"),
    t("Presentation : 0,25 pt",
      "Presentation: 0.25 pt"),
  ],

  // ===================== PROBATOIRE A 2023 =====================
  2023: [
    main("L'epreuve de mathematiques du PROBATOIRE A 2023", "Mathematics Exam - Probatoire A 2023"),

    sec("Partie A : Evaluation des ressources", "15 points", "Part A: Resource Assessment"),

    ex("Exercice 1 :", "4 points", "Exercise 1:"),
    t("1. Determiner tous les couples $(x,y)$ de $\\mathbb{R}^2$ solutions du systeme : 2 pts",
      "1. Determine all pairs $(x,y)$ in $\\mathbb{R}^2$ that are solutions of the system: 2 pts"),
    t("$(S):\\begin{cases} 14x+8y=222 \\\\ x+y=21 \\end{cases}$"),
    t("Un camion de marchandises transporte 21 sacs constitues uniquement de sacs de haricot et de sacs de mais.",
      "A merchandise truck transports 21 bags consisting only of bean bags and corn bags."),
    t("Un sac de haricot pese $140$ kg tandis qu'un sac de mais pese $80$ kg.",
      "A bag of beans weighs $140$ kg while a bag of corn weighs $80$ kg."),
    t("Le pesage routier releve que le camion transporte une charge totale de $2\\,220$ kg.",
      "The road weighing shows that the truck carries a total load of $2,220$ kg."),
    t("$a$ et $b$ designent respectivement le nombre de sacs de haricot et le nombre de sacs de mais charges dans ce camion.",
      "$a$ and $b$ designate respectively the number of bean bags and corn bags loaded in this truck."),
    t("a) Montrer que $a$ et $b$ verifient le systeme $(S)$. 1 pt",
      "a) Show that $a$ and $b$ satisfy the system $(S)$. 1 pt"),
    t("b) Calculer le nombre de sacs de haricot et le nombre de sacs de mais que transporte ce camion. 1 pt",
      "b) Calculate the number of bean bags and corn bags that this truck carries. 1 pt"),

    ex("Exercice 2 :", "6 points", "Exercise 2:"),
    t("1. Une couturiere a dans une boite opaque (non transparente), 27 boutons indiscernables au toucher, dont 5 noirs, 10 blancs et 12 rouges.",
      "1. A seamstress has in an opaque (non-transparent) box, 27 buttons indistinguishable by touch, including 5 black, 10 white and 12 red."),
    t("Elle prend simultanement 5 boutons de cette boite.",
      "She simultaneously takes 5 buttons from this box."),
    t("a) Determiner le nombre de prises possibles. 1 pt",
      "a) Determine the number of possible draws. 1 pt"),
    t("b) Determiner le nombre de prises comportant exactement 3 boutons rouges. 1,5 pt",
      "b) Determine the number of draws containing exactly 3 red buttons. 1.5 pt"),
    t("2. Le tableau ci-dessous represente les masses corporelles en kilogramme, des enfants internes d'une pediatrie un lundi matin.",
      "2. The table below represents the body masses in kilograms of children admitted to a pediatric ward on a Monday morning."),
    tbl("$\\begin{array}{|c|c|c|c|c|c|}\\hline \\text{Masse corporelle} & [0\\;;2[ & [2\\;;4[ & [4\\;;6[ & [6\\;;8[ & [8\\;;10[ \\\\ \\hline \\text{Effectifs} & 5 & 6 & 4 & 3 & 2 \\\\ \\hline \\end{array}$",
      "$\\begin{array}{|c|c|c|c|c|c|}\\hline \\text{Body mass} & [0;2[ & [2;4[ & [4;6[ & [6;8[ & [8;10[ \\\\ \\hline \\text{Frequencies} & 5 & 6 & 4 & 3 & 2 \\\\ \\hline \\end{array}$"),
    t("a) Calculer la moyenne des masses corporelles de ces enfants. 1 pt",
      "a) Calculate the average body mass of these children. 1 pt"),
    t("b) i) Reproduire le tableau ci-dessus et le completer par la ligne des effectifs cumules croissants. 1,25 pt",
      "b) i) Reproduce the table above and complete it with the row of cumulative increasing frequencies. 1.25 pt"),
    t("ii) En deduire la classe mediane de cette serie. 0,25 pt",
      "ii) Deduce the median class of this series. 0.25 pt"),
    t("c) Construire l'histogramme de cette serie. 1 pt",
      "c) Construct the histogram of this series. 1 pt"),

    ex("Exercice 3 :", "5 points", "Exercise 3:"),
    t("Le plan est muni d'un repere orthonorme $(O;I,J)$. L'unite sur les axes est $1$ cm.",
      "The plane is equipped with an orthonormal coordinate system $(O;I,J)$. The unit on the axes is $1$ cm."),
    t("Soit $f$ la fonction definie sur $[0\\;;4]$ par $f(x)=x^2-4x+5$.",
      "Let $f$ be the function defined on $[0;4]$ by $f(x)=x^2-4x+5$."),
    t("On note $(C)$ sa courbe representative.",
      "$(C)$ denotes its representative curve."),
    t("1. a) Calculer $f'(x)$. 0,5 pt",
      "1. a) Calculate $f'(x)$. 0.5 pt"),
    t("b) Dresser le tableau des variations de la fonction $f$. 2 pts",
      "b) Draw the table of variations of the function $f$. 2 pts"),
    t("2. Determiner une equation cartesienne de la tangente $(T)$ a $(C)$ au point d'abscisse $x_0=3$. 0,75 pt",
      "2. Determine a Cartesian equation of the tangent $(T)$ to $(C)$ at the point with x-coordinate $x_0=3$. 0.75 pt"),
    t("3. Construire $(C)$ et $(T)$. 1,75 pt",
      "3. Construct $(C)$ and $(T)$. 1.75 pt"),

    sec("Partie B : Evaluation des competences", "5 points", "Part B: Skills Assessment"),

    subsec("Situation :", "", "Situation:"),
    t("Talor est un grand jardinier qui travaille dans un jardin $j$ ayant la forme d'un triangle rectangle d'aire $9\\,600$ m$^2$. Le plus petit cote de l'angle droit est borde d'une grande route. Il se souvient que la somme des mesures des deux cotes de l'angle droit de ce jardin est $280$ m.",
      "Talor is a great gardener who works in a garden $j$ shaped like a right-angled triangle with an area of $9,600$ m$^2$. The shortest side of the right angle borders a main road. He remembers that the sum of the two sides of the right angle of this garden is $280$ m."),
    t("Pour eviter que les usagers de la route n'entrent dans son jardin, il s'est decide a proteger cette limite avec la route, d'une ligne de fil barbele. Mais, il ne dispose d'aucun instrument pour mesurer la longueur de cette limite.",
      "To prevent road users from entering his garden, he decided to protect this boundary with the road using barbed wire. However, he has no instrument to measure the length of this boundary."),
    t("Talor a produit des tomates qu'il compte vendre sur le marche de la place ou le cageot coutait $6\\,000$ frs le mois dernier. Une fois sur le marche, il apprend que les fruits et legumes ont subi deux hausses successives de meme taux $(x\\%)$. Et que le seau de carottes qui se vendait a $5\\,000$ frs avant les deux hausses coute maintenant $5\\,408$ frs. Rapidement, il cherche a ajuster le prix des tomates.",
      "Talor has produced tomatoes that he plans to sell at the local market where a crate cost $6,000$ frs last month. At the market, he learns that fruits and vegetables have undergone two successive increases at the same rate $(x\\%)$. And that the bucket of carrots that sold for $5,000$ frs before the two increases now costs $5,408$ frs. He quickly tries to adjust the price of tomatoes."),
    t("La quantite $q$ en kg de tomates produites est une fonction du nombre d'annees $t\\in[1\\;;10]$ d'exploitation du jardin ; cette fonction est definie par : $q(t)=-t^2+10t-5$.",
      "The quantity $q$ in kg of tomatoes produced is a function of the number of years $t\\in[1;10]$ of garden exploitation; this function is defined by: $q(t)=-t^2+10t-5$."),
    img("/images/proba-a-2023-geo.jpg", "Schema du jardin triangulaire de Talor"),

    subsec("Taches :", "", "Tasks:"),
    t("1. Determiner pour Talor, la longueur de fil barbele utile pour cette protection. 1,5 pt",
      "1. Determine for Talor, the length of barbed wire needed for this protection. 1.5 pt"),
    t("2. Determiner combien Talor doit vendre un cageot de tomates. 1,5 pt",
      "2. Determine how much Talor should sell a crate of tomatoes for. 1.5 pt"),
    t("3. Determiner le rang de l'annee dont la production des tomates sera maximale sur ce jardin, et cette production maximale. 1,5 pt",
      "3. Determine the year in which tomato production will be maximum in this garden, and this maximum production. 1.5 pt"),
    t("Presentation : 0,5 pt",
      "Presentation: 0.5 pt"),
  ],

  // ===================== PROBATOIRE A 2022 =====================
  2022: [
    main("L'epreuve de mathematiques du PROBATOIRE A 2022", "Mathematics Exam - Probatoire A 2022"),

    sec("Partie A : Evaluation des ressources", "5 points", "Part A: Resource Assessment"),

    ex("Exercice 1 :", "5 points", "Exercise 1:"),
    t("Le resultat d'une enquete menee sur le temps mis en minutes par chaque eleve d'une classe pour partir de son domicile a sa classe est consigne dans le tableau ci-dessous :",
      "The result of a survey on the time in minutes taken by each student in a class to go from home to class is recorded in the table below:"),
    tbl("$\\begin{array}{|c|c|c|c|c|c|}\\hline \\text{Temps mis (en min)} & [0\\;;10[ & [10\\;;20[ & [20\\;;30[ & [30\\;;40[ & [40\\;;50[ \\\\ \\hline \\text{Effectifs} & 6 & 3 & 4 & 5 & 2 \\\\ \\hline \\end{array}$",
      "$\\begin{array}{|c|c|c|c|c|c|}\\hline \\text{Time (in min)} & [0;10[ & [10;20[ & [20;30[ & [30;40[ & [40;50[ \\\\ \\hline \\text{Frequencies} & 6 & 3 & 4 & 5 & 2 \\\\ \\hline \\end{array}$"),
    t("1. Calculer la moyenne des temps mis par les eleves de cette classe pour partir de leurs domiciles a leurs classes. 1 pt",
      "1. Calculate the average time taken by students in this class to go from their homes to their classes. 1 pt"),
    t("2. Construire le polygone des effectifs cumules croissants de cette serie statistique : prendre 1 cm pour 5 minutes et 1 cm pour 5 eleves. 2 pts",
      "2. Construct the cumulative frequency polygon of this statistical series: use 1 cm for 5 minutes and 1 cm for 5 students. 2 pts"),
    t("3. On choisit au hasard et simultanement deux eleves parmi ceux qui mettent moins de 10 minutes pour regagner leur classe. Deux parmi ces 6 eleves sont des filles.",
      "3. Two students are chosen at random simultaneously from those who take less than 10 minutes to reach their class. Two of these 6 students are girls."),
    t("a) Combien y a-t-il de choix possibles ? 1 pt",
      "a) How many possible choices are there? 1 pt"),
    t("b) Combien y a-t-il de choix possibles ne contenant que des garcons ? 1 pt",
      "b) How many possible choices contain only boys? 1 pt"),

    ex("Exercice 2 :", "5,5 points", "Exercise 2:"),
    t("On considere la fonction $g$ definie sur $[-3\\;;7]$ par $g(x)=\\dfrac{x+a}{x+b}$ ou $a$ et $b$ sont des nombres reels.",
      "Consider the function $g$ defined on $[-3;7]$ by $g(x)=\\dfrac{x+a}{x+b}$ where $a$ and $b$ are real numbers."),
    t("1. Determiner $a$ et $b$ pour que la courbe de $g$ passe par les points $A(-3\\;;0)$ et $B(7\\;;2)$. 1 pt",
      "1. Determine $a$ and $b$ so that the curve of $g$ passes through points $A(-3;0)$ and $B(7;2)$. 1 pt"),
    t("2. On considere la fonction $f$ definie sur $[-3\\;;7]$ par $f(x)=1+\\dfrac{5}{x-2}$.",
      "2. Consider the function $f$ defined on $[-3;7]$ by $f(x)=1+\\dfrac{5}{x-2}$."),
    t("a) Determiner l'ensemble de definition $E$ de la fonction $f$. 0,5 pt",
      "a) Determine the domain $E$ of the function $f$. 0.5 pt"),
    t("b) Calculer $\\displaystyle\\lim_{x\\to 2^-} f(x)$ et $\\displaystyle\\lim_{x\\to 2^+} f(x)$ puis en deduire que la droite $(D)$ d'equation $x=2$ est une asymptote a la courbe de $f$. 1 pt",
      "b) Calculate $\\displaystyle\\lim_{x\\to 2^-} f(x)$ and $\\displaystyle\\lim_{x\\to 2^+} f(x)$ then deduce that the line $(D)$ with equation $x=2$ is an asymptote to the curve of $f$. 1 pt"),
    t("c) Justifier que sur $E$, la derivee $f'$ de $f$ est definie par : $f'(x)=\\dfrac{-5}{(x-2)^2}$, pour tout reel $x\\neq 2$. 0,5 pt",
      "c) Justify that on $E$, the derivative $f'$ of $f$ is defined by: $f'(x)=\\dfrac{-5}{(x-2)^2}$, for all real $x\\neq 2$. 0.5 pt"),
    t("d) En deduire le sens de variations de $f$. 0,5 pt",
      "d) Deduce the direction of variation of $f$. 0.5 pt"),
    t("e) Dresser le tableau de variations de $f$. 0,5 pt",
      "e) Draw the table of variations of $f$. 0.5 pt"),
    t("f) Construire la courbe $(C)$ de $f$ et la droite $(D)$ dans un repere orthonorme. 1,5 pt",
      "f) Construct the curve $(C)$ of $f$ and the line $(D)$ in an orthonormal coordinate system. 1.5 pt"),

    ex("Exercice 3 :", "4,5 points", "Exercise 3:"),
    t("1. Resoudre dans $\\mathbb{R}$ l'equation $(E): x^2-41x+408=0$ et l'inequation $(I): x^2-41x+408\\le 408$ d'inconnue $x$. 1 pt",
      "1. Solve in $\\mathbb{R}$ the equation $(E): x^2-41x+408=0$ and the inequality $(I): x^2-41x+408\\le 408$ with unknown $x$. 1 pt"),
    t("2. Bouba a un terrain de forme rectangulaire d'aire $408$ m$^2$ et de perimetre $82$ m.",
      "2. Bouba has a rectangular piece of land with area $408$ m$^2$ and perimeter $82$ m."),
    t("a) Justifier que les dimensions de ce terrain sont les solutions de l'equation $(E)$. 1,25 pt",
      "a) Justify that the dimensions of this land are the solutions of equation $(E)$. 1.25 pt"),
    t("b) En deduire la longueur $L$ et la largeur $l$ de ce terrain. 2,25 pts",
      "b) Deduce the length $L$ and width $l$ of this land. 2.25 pts"),

    sec("Partie B : Evaluation des competences", "5 points", "Part B: Skills Assessment"),

    subsec("Situation :", "", "Situation:"),
    t("Dans un magasin, deux baisses de meme taux ont lieu en decembre sur le prix de chaque article. Un sac qui coutait $11\\,000$ F est vendu a $10\\,120$ F apres la 1ere baisse.",
      "In a store, two price reductions at the same rate take place in December on every item. A bag that cost $11,000$ F is sold at $10,120$ F after the 1st reduction."),
    t("A l'occasion de son mariage et apres la 2eme baisse, Fred ne dispose que de $8\\,500$ F pour acheter une bague qui coutait $10\\,000$ F avant la 1ere baisse.",
      "For his wedding and after the 2nd reduction, Fred only has $8,500$ F to buy a ring that cost $10,000$ F before the 1st reduction."),
    t("Pour son cadeau de mariage, le groupe GES voudrait lui acheter un lit a $154\\,000$ F, et les membres de ce groupe se repartissent equitablement les depenses. Deux d'entre eux declarent leur incapacite a payer, et chacun des autres membres voit sa contribution augmenter de $8\\,800$ F. Le jour du mariage, une table et six chaises sont reservees a tous les membres de ce groupe.",
      "For his wedding gift, the GES group wants to buy him a bed for $154,000$ F, and the group members share the expenses equally. Two of them declare their inability to pay, and each of the other members sees their contribution increase by $8,800$ F. On the wedding day, a table and six chairs are reserved for all members of this group."),
    t("Pour un album souvenir, les six freres de Fred voudraient former le maximum d'equipes de 3 freres pour se filmer avec les maries ce jour. Pour cela, ils reservent $8\\,000$ F pour ces photos. Chaque equipe n'a droit qu'a une et une seule photo qui coute $425$ F. A la fin de la ceremonie, toutes les photos prevues ont ete prises.",
      "For a souvenir album, Fred's six brothers want to form the maximum number of teams of 3 brothers to be filmed with the newlyweds. They reserve $8,000$ F for these photos. Each team is entitled to one and only one photo costing $425$ F. At the end of the ceremony, all planned photos were taken."),

    subsec("Taches :", "", "Tasks:"),
    t("1. La somme d'argent dont dispose Fred lui permettra-t-elle d'acheter sa bague ? 1,5 pt",
      "1. Will the amount of money Fred has allow him to buy his ring? 1.5 pt"),
    t("2. Le nombre de places reservees aux membres du groupe GES le jour du mariage suffira-t-il ? 1,5 pt",
      "2. Will the number of seats reserved for GES group members on the wedding day be enough? 1.5 pt"),
    t("3. La somme reservee par les six freres de Fred suffira-t-elle pour payer toutes les photos prevues ? 1,5 pt",
      "3. Will the amount reserved by Fred's six brothers be enough to pay for all planned photos? 1.5 pt"),
    t("Presentation : 0,5 pt",
      "Presentation: 0.5 pt"),
  ],

  // ===================== PROBATOIRE A 2021 =====================
  2021: [
    main("L'epreuve de mathematiques du PROBATOIRE A 2021", "Mathematics Exam - Probatoire A 2021"),

    sec("Partie A : Evaluation des ressources", "15 points", "Part A: Resource Assessment"),

    ex("Exercice 1 :", "4 points", "Exercise 1:"),
    t("1. a) Determiner les solutions dans $\\mathbb{R}$ de l'equation $x^2-50x+600=0$. 1 pt",
      "1. a) Determine the solutions in $\\mathbb{R}$ of the equation $x^2-50x+600=0$. 1 pt"),
    t("b) Determiner l'ensemble solution dans $\\mathbb{R}$ de l'inequation $x^2-50x+600\\ge 0$. 1 pt",
      "b) Determine the solution set in $\\mathbb{R}$ of the inequality $x^2-50x+600\\ge 0$. 1 pt"),
    t("2. Repondre par vrai ou faux. Les couples solutions dans $\\mathbb{R}^2$ du systeme d'equations $\\begin{cases} xy=600 \\\\ x+y=50 \\end{cases}$ sont $(20;30)$ et $(-30;-20)$. 1 pt",
      "2. Answer true or false. The solution pairs in $\\mathbb{R}^2$ of the system $\\begin{cases} xy=600 \\\\ x+y=50 \\end{cases}$ are $(20;30)$ and $(-30;-20)$. 1 pt"),
    t("3. Un terrain rectangulaire a pour perimetre $100$ metres et pour aire $600$ m$^2$. Determiner les dimensions de ce terrain. 1 pt",
      "3. A rectangular piece of land has a perimeter of $100$ meters and an area of $600$ m$^2$. Determine the dimensions of this land. 1 pt"),

    ex("Exercice 2 :", "5,5 points", "Exercise 2:"),
    t("Le tableau suivant donne la repartition des ages des employes d'une entreprise.",
      "The following table gives the age distribution of employees of a company."),
    tbl("$\\begin{array}{|c|c|c|c|c|}\\hline \\text{Classes d'age} & [20\\;;30[ & [30\\;;40[ & [40\\;;50[ & [50\\;;60[ \\\\ \\hline \\text{Effectifs} & 8 & 16 & 24 & 12 \\\\ \\hline \\text{Effectifs cumules croissants} & 8 & & & \\\\ \\hline \\end{array}$",
      "$\\begin{array}{|c|c|c|c|c|}\\hline \\text{Age classes} & [20;30[ & [30;40[ & [40;50[ & [50;60[ \\\\ \\hline \\text{Frequencies} & 8 & 16 & 24 & 12 \\\\ \\hline \\text{Cumulative frequencies} & 8 & & & \\\\ \\hline \\end{array}$"),
    t("1. Calculer l'age moyen des employes de cette entreprise. 1 pt",
      "1. Calculate the average age of employees of this company. 1 pt"),
    t("2. Reproduire ce tableau statistique puis completer la ligne des effectifs cumules croissants. 1 pt",
      "2. Reproduce this statistical table and complete the row of cumulative increasing frequencies. 1 pt"),
    t("3. a) Construire le polygone des effectifs cumules croissants de cette serie statistique. Prendre $1$ cm pour $5$ sur les axes. 1,5 pt",
      "3. a) Construct the cumulative frequency polygon of this statistical series. Use $1$ cm for $5$ on the axes. 1.5 pt"),
    t("b) Lire et marquer sur le graphique, la mediane de cette serie statistique. 0,5 pt",
      "b) Read and mark on the graph, the median of this statistical series. 0.5 pt"),
    t("4. Les $60$ employes de cette entreprise decident d'emprunter un bus de $60$ places assises pour se rendre a une excursion. Avant le voyage ils decident de choisir un groupe de trois encadreurs parmi les employes dont l'age est superieur ou egal a $50$ ans.",
      "4. The $60$ employees of this company decide to take a $60$-seat bus for an excursion. Before the trip they decide to choose a group of three supervisors from employees aged $50$ or over."),
    t("a) Determiner le nombre de facons differentes pour les employes de cette entreprise de prendre place dans le bus au moment du depart. 0,75 pt",
      "a) Determine the number of different ways for employees to take their seats in the bus at departure. 0.75 pt"),
    t("b) Determiner le nombre de groupes d'encadreurs differents que l'on peut choisir. 0,75 pt",
      "b) Determine the number of different groups of supervisors that can be chosen. 0.75 pt"),

    ex("Exercice 3 :", "5,5 points", "Exercise 3:"),
    t("La courbe representative $(C_f)$ ci-apres est celle d'une fonction numerique $f$.",
      "The representative curve $(C_f)$ below is that of a numerical function $f$."),
    img("/images/proba-a-2021-courbe.jpg", "Courbe representative de la fonction f"),
    t("1. Par lecture graphique, determiner :",
      "1. By graphical reading, determine:"),
    t("a) L'ensemble de definition de la fonction $f$. 0,5 pt",
      "a) The domain of the function $f$. 0.5 pt"),
    t("b) $f(0)$ et $f(2)$. 0,5 pt",
      "b) $f(0)$ and $f(2)$. 0.5 pt"),
    t("c) L'ensemble solution de l'inequation $f(x)\\ge 0$. 0,5 pt",
      "c) The solution set of the inequality $f(x)\\ge 0$. 0.5 pt"),
    t("d) Les limites de $f$ a gauche et a droite en $1$. 0,5 pt",
      "d) The limits of $f$ to the left and right at $1$. 0.5 pt"),
    t("e) Le sens de variation de $f$ sur $[-4\\;;1[$ et sur $]1\\;;4]$. 0,5 pt",
      "e) The direction of variation of $f$ on $[-4;1[$ and on $]1;4]$. 0.5 pt"),
    t("2. On suppose que la fonction $f$ est definie pour tout $x\\neq 1$ par $f(x)=\\dfrac{ax+b}{x-1}$ ou $a$ et $b$ sont des nombres reels.",
      "2. Assume that the function $f$ is defined for all $x\\neq 1$ by $f(x)=\\dfrac{ax+b}{x-1}$ where $a$ and $b$ are real numbers."),
    t("a) En utilisant la question 1.b), montrer que $a=1$ et $b=-2$. 1 pt",
      "a) Using question 1.b), show that $a=1$ and $b=-2$. 1 pt"),
    t("b) Determiner une equation de la tangente a $(C_f)$ au point d'abscisse $2$. 1 pt",
      "b) Determine an equation of the tangent to $(C_f)$ at the point with x-coordinate $2$. 1 pt"),
    t("3. Reproduire la courbe $(C_f)$ puis construire dans le meme repere, la courbe $(C_g)$ de la fonction $g$: $x\\mapsto |f(x)|$. 1 pt",
      "3. Reproduce the curve $(C_f)$ then construct in the same coordinate system, the curve $(C_g)$ of the function $g$: $x\\mapsto |f(x)|$. 1 pt"),

    sec("Partie B : Evaluation des competences", "5 points", "Part B: Skills Assessment"),

    subsec("Situation :", "", "Situation:"),
    t("M. BALLA, parent d'eleves a prevu la somme de $6\\,000$ F CFA a partager equitablement entre ses enfants, pour l'argent de poche de la semaine. Mais avant la rentree scolaire, il accueille chez lui ses deux neveux. Faute de moyens supplementaires, il decide alors de partager equitablement la meme somme a tous les enfants, y compris ses deux neveux ; la part de chacun de ses propres enfants se retrouve alors diminuee de $500$ FCFA.",
      "Mr. BALLA, a parent, has planned a sum of $6,000$ F CFA to share equally among his children for weekly pocket money. But before the school year, he takes in his two nephews. Lacking additional funds, he decides to share the same sum equally among all children, including his two nephews; each of his own children's share is then reduced by $500$ FCFA."),
    t("Pour pouvoir heberger ses deux neveux, il veut amenager une chambre rectangulaire d'aire $15{,}75$ m$^2$ et de perimetre $16$ metres.",
      "To house his two nephews, he wants to set up a rectangular room with an area of $15.75$ m$^2$ and a perimeter of $16$ meters."),
    t("Pour la nutrition de tous les enfants, il a effectue deux mois de suite, des achats dans un magasin dont les prix n'ont pas change pendant les deux mois. Le premier mois, il a ainsi achete $2$ sacs de riz de $25$ kg et $2$ bidons d'huile de $5$ litres a $38\\,000$ F CFA. Le mois suivant, il a achete $1$ sac de riz de $25$ kg et $2$ bidons d'huile a $25\\,500$ F CFA.",
      "For the nutrition of all children, he made purchases for two consecutive months at a store where prices did not change. The first month, he bought $2$ bags of rice of $25$ kg and $2$ cans of oil of $5$ liters for $38,000$ F CFA. The following month, he bought $1$ bag of rice of $25$ kg and $2$ cans of oil for $25,500$ F CFA."),

    subsec("Taches :", "", "Tasks:"),
    t("1. Determiner le nombre d'enfants propres de M. BALLA. 1,5 pt",
      "1. Determine the number of Mr. BALLA's own children. 1.5 pt"),
    t("2. Determiner les dimensions de la chambre que M. BALLA veut amenager pour ses deux neveux. 1,5 pt",
      "2. Determine the dimensions of the room Mr. BALLA wants to set up for his two nephews. 1.5 pt"),
    t("3. Determiner le prix d'un sac de riz et le prix d'un bidon d'huile achetes par M. BALLA. 1,5 pt",
      "3. Determine the price of a bag of rice and the price of a can of oil bought by Mr. BALLA. 1.5 pt"),
    t("Presentation : 0,5 pt",
      "Presentation: 0.5 pt"),
  ],

  // ===================== PROBATOIRE A 2020 =====================
  2020: [
    main("L'epreuve de mathematiques du PROBATOIRE A 2020", "Mathematics Exam - Probatoire A 2020"),

    sec("Partie A : Evaluation des ressources", "15 points", "Part A: Resource Assessment"),

    ex("Exercice 1 :", "6 points", "Exercise 1:"),

    subsec("I- QCM : Pour chaque question suivante, trois reponses sont proposees parmi lesquelles une seule est juste.", "", "I- MCQ: For each question, three answers are proposed, only one is correct."),

    t("1. La forme canonique du polynome $x^2+x-2$ est : 0,5 pt",
      "1. The canonical form of the polynomial $x^2+x-2$ is: 0.5 pt"),
    t("a) $\\left(x+\\dfrac{1}{2}\\right)^2-\\dfrac{9}{4}$ ; b) $\\left(x-\\dfrac{1}{2}\\right)^2+\\dfrac{9}{4}$ ; c) $\\left(x+\\dfrac{1}{2}\\right)^2+\\dfrac{9}{4}$."),

    t("2. L'equation $-\\dfrac{18}{39}x^2+\\sqrt{3}x+\\dfrac{41}{109}$ admet dans $\\mathbb{R}$ : 0,5 pt",
      "2. The equation $-\\dfrac{18}{39}x^2+\\sqrt{3}x+\\dfrac{41}{109}$ admits in $\\mathbb{R}$: 0.5 pt"),
    t("a) Deux solutions ; b) Une seule solution ; c) Zero solution.",
      "a) Two solutions; b) One solution; c) Zero solutions."),

    t("3. Deux nombres reels positifs, dont la somme est 21 et le produit 104, sont solutions de l'equation : 0,5 pt",
      "3. Two positive real numbers, whose sum is 21 and product 104, are solutions of the equation: 0.5 pt"),
    t("a) $x^2-104x-21=0$ ; b) $x^2+21x+104=0$ ; c) $x^2-21x+104=0$."),

    t("4. L'ensemble solution de l'inequation $x^2-2x+1\\le 0$ est : 0,5 pt",
      "4. The solution set of the inequality $x^2-2x+1\\le 0$ is: 0.5 pt"),
    t("a) $\\mathbb{R}$ ; b) $\\varnothing$ ; c) $\\{1\\}$."),

    t("5. Le couple $(x;y)$ de nombres reels solution du systeme $\\begin{cases} 3x-y=5 \\\\ -x+3y=1 \\end{cases}$ est : 0,5 pt",
      "5. The pair $(x;y)$ of real numbers solution of the system $\\begin{cases} 3x-y=5 \\\\ -x+3y=1 \\end{cases}$ is: 0.5 pt"),
    t("a) $(1;2)$ ; b) $(2;1)$ ; c) $(3;4)$."),

    subsec("II- Urne : Une urne contient 5 boules distinctes et indiscernables au toucher : 2 boules vertes et 3 boules rouges.", "", "II- Urn: An urn contains 5 distinct balls indistinguishable by touch: 2 green and 3 red balls."),

    t("1. On tire au hasard et simultanement 2 boules de l'urne.",
      "1. Two balls are drawn simultaneously and at random from the urn."),
    t("a) Combien de tirages differents peut-on ainsi effectuer ? 0,5 pt",
      "a) How many different draws can be made? 0.5 pt"),
    t("b) Determiner le nombre de tirages differents pour lesquels les 2 boules sont de couleurs differentes. 0,5 pt",
      "b) Determine the number of different draws for which the 2 balls are of different colors. 0.5 pt"),
    t("c) Determiner le nombre de tirages differents pour lesquels les 2 boules sont de meme couleur. 0,5 pt",
      "c) Determine the number of different draws for which the 2 balls are the same color. 0.5 pt"),

    t("2. On tire au hasard et successivement 2 boules sans remise.",
      "2. Two balls are drawn successively without replacement."),
    t("a) Combien de tirages differents peut-on ainsi effectuer ? 0,5 pt",
      "a) How many different draws can be made? 0.5 pt"),
    t("b) Determiner le nombre de tirages differents pour lesquels les 2 boules sont de couleurs differentes. 0,5 pt",
      "b) Determine the number of different draws for which the 2 balls are of different colors. 0.5 pt"),
    t("c) Determiner le nombre de tirages differents pour lesquels les 2 boules sont de meme couleur. 0,5 pt",
      "c) Determine the number of different draws for which the 2 balls are the same color. 0.5 pt"),

    ex("Exercice 2 :", "4 points", "Exercise 2:"),
    t("A l'issue d'une evaluation, les notes (sur 20) de Mathematiques obtenues par 100 eleves d'une classe de premiere litteraire ont ete regroupees en classes dans le tableau suivant :",
      "After an assessment, the Mathematics grades (out of 20) obtained by 100 students in a first-year literary class are grouped in the following table:"),
    tbl("$\\begin{array}{|c|c|c|c|c|c|}\\hline \\text{Notes} & [0\\;;4[ & [4\\;;8[ & [8\\;;12[ & [12\\;;16[ & [16\\;;20[ \\\\ \\hline \\text{Frequences } (f_i) & 10\\% & 30\\% & 20\\% & 25\\% & 15\\% \\\\ \\hline \\end{array}$",
      "$\\begin{array}{|c|c|c|c|c|c|}\\hline \\text{Grades} & [0;4[ & [4;8[ & [8;12[ & [12;16[ & [16;20[ \\\\ \\hline \\text{Frequencies } (f_i) & 10\\% & 30\\% & 20\\% & 25\\% & 15\\% \\\\ \\hline \\end{array}$"),
    t("1. a) Calculer la moyenne de cette serie. 1 pt",
      "1. a) Calculate the mean of this series. 1 pt"),
    t("b) Calculer la variance et l'ecart-type de cette serie. 0,5 pt",
      "b) Calculate the variance and standard deviation of this series. 0.5 pt"),
    t("2. Reproduire et completer le tableau avec les frequences cumulees croissantes. 0,75 pt",
      "2. Reproduce and complete the table with cumulative increasing frequencies. 0.75 pt"),
    t("3. Construire le polygone des frequences cumulees croissantes. 1,25 pt",
      "3. Construct the cumulative frequency polygon. 1.25 pt"),
    t("4. Determiner par lecture graphique la mediane de cette serie. 0,5 pt",
      "4. Determine by graphical reading the median of this series. 0.5 pt"),

    ex("Exercice 3 :", "5 points", "Exercise 3:"),
    t("Le plan est muni d'un repere orthonorme $(O,I,J)$ d'unite sur les axes, 1 cm. Soit $f$ la fonction definie sur $[-1\\;;5]$ par : $f(x)=-x^2+4x-1$. On note $(C)$ sa courbe representative.",
      "The plane is equipped with an orthonormal coordinate system $(O,I,J)$ with unit 1 cm on the axes. Let $f$ be the function defined on $[-1;5]$ by: $f(x)=-x^2+4x-1$. $(C)$ denotes its representative curve."),
    t("1. Calculer $\\displaystyle\\lim_{x\\to -1^+} f(x)$ et $\\displaystyle\\lim_{x\\to 5^-} f(x)$. 0,5 pt",
      "1. Calculate $\\displaystyle\\lim_{x\\to -1^+} f(x)$ and $\\displaystyle\\lim_{x\\to 5^-} f(x)$. 0.5 pt"),
    t("2. Determiner la fonction derivee $f'$ de $f$ et dresser son tableau de variations. 1,5 pt",
      "2. Determine the derivative function $f'$ of $f$ and draw its table of variations. 1.5 pt"),
    t("3. Determiner une equation cartesienne de la tangente a $(C)$ au point d'abscisse 3. 1 pt",
      "3. Determine a Cartesian equation of the tangent to $(C)$ at the point with x-coordinate 3. 1 pt"),
    t("4. Construire $(C)$. 1 pt",
      "4. Construct $(C)$. 1 pt"),
    t("5. Construire sur le meme repere la courbe de la fonction $g$ definie par : $g(x)=f(x-1)$. 1 pt",
      "5. Construct on the same coordinate system the curve of the function $g$ defined by: $g(x)=f(x-1)$. 1 pt"),

    sec("Partie B : Evaluation des competences", "5 points", "Part B: Skills Assessment"),

    subsec("Situation :", "", "Situation:"),
    t("Pour la realisation d'un projet de construction, Monsieur AKONO avait place une somme de $8\\,064\\,000$ FCFA dans une banque a interets annuels composes.",
      "For a construction project, Mr. AKONO had placed a sum of $8,064,000$ FCFA in a bank with annual compound interest."),
    t("Malheureusement, il decede trois mois plus tard. Dans le but de realiser ce projet, son epouse decide de retirer, deux ans plus tard, cette somme pour acheter un terrain rectangulaire de $2\\,016$ m$^2$ dont la longueur depasse la largeur de $6$ m.",
      "Unfortunately, he passes away three months later. To carry out the project, his wife decides to withdraw, two years later, this sum to buy a rectangular plot of $2,016$ m$^2$ whose length exceeds the width by $6$ m."),
    t("Mais lors du retrait, elle est agreablement surprise de constater que l'argent place par son defunt epoux a produit en deux ans un interet de $423\\,360$ FCFA et elle se demande bien quel interet elle obtiendrait au bout d'un an si elle place aussi dans cette banque, la meme somme que son defunt epoux.",
      "But upon withdrawal, she is pleasantly surprised to find that the money placed by her late husband earned $423,360$ FCFA in interest over two years, and she wonders what interest she would earn after one year if she placed the same amount in this bank."),
    t("Madame AKONO veut entourer le terrain rectangulaire qu'elle vient d'acheter, de piquets regulierement espaces de $6$ m en mettant un piquet a chaque coin du terrain.",
      "Mrs. AKONO wants to surround the rectangular plot she just bought with stakes regularly spaced $6$ m apart, placing a stake at each corner."),
    t("Par ailleurs, elle aimerait utiliser l'interet percu ($423\\,360$ FCFA) pour acheter un camion de sable et $48$ sacs de ciment.",
      "Furthermore, she would like to use the interest earned ($423,360$ FCFA) to buy a truckload of sand and $48$ bags of cement."),
    t("Elle se rappelle que son amie a achete, il y a de cela quelques jours, aux memes prix deux camions de sable et $20$ sacs de ciment pour un montant total de $466\\,720$ FCFA.",
      "She remembers that her friend bought, a few days ago, at the same prices, two truckloads of sand and $20$ bags of cement for a total of $466,720$ FCFA."),

    subsec("Taches :", "", "Tasks:"),
    t("1. Quel est l'interet qu'obtiendrait Madame AKONO au bout d'un an, si elle placait la meme somme que son epoux dans cette banque ? 1,5 pt",
      "1. What interest would Mrs. AKONO earn after one year if she placed the same amount as her husband in this bank? 1.5 pt"),
    t("2. De combien de piquets Madame AKONO a-t-elle besoin pour entourer son terrain ? 1,5 pt",
      "2. How many stakes does Mrs. AKONO need to surround her plot? 1.5 pt"),
    t("3. Quel est le prix d'un sac de ciment et celui d'un camion de sable que Madame AKONO doit prevoir pour faire ses achats ? 1,5 pt",
      "3. What is the price of a bag of cement and a truckload of sand that Mrs. AKONO should budget for? 1.5 pt"),
    t("Presentation : 0,5 pt",
      "Presentation: 0.5 pt"),
  ],

  // ===================== PROBATOIRE A 2019 =====================
  2019: [
    main("L'epreuve de mathematiques du PROBATOIRE A 2019", "Mathematics Exam - Probatoire A 2019"),

    sec("Partie A :", "6 points", "Part A:"),

    t("1. Resoudre dans $\\mathbb{R}$, l'equation $(E) : x^2+400x-262\\,500=0$. 2 pts",
      "1. Solve in $\\mathbb{R}$, the equation $(E): x^2+400x-262\\,500=0$. 2 pts"),
    t("2) Pour assister a une edition de la coupe de football du Cameroun, un groupe de supporters veut quitter une localite $A$ pour se rendre a Yaounde. Il decide de reserver des bus dans une agence de voyage. Les clauses de la negociation sont les suivantes :",
      "2) To attend an edition of the Cameroon football cup, a group of supporters wants to leave a locality $A$ for Yaounde. They decide to book buses at a travel agency. The terms of the negotiation are:"),
    t("Si le groupe est seul, il paye $875\\,000$ F.",
      "If the group is alone, they pay $875,000$ F."),
    t("S'il y a 150 supporters de plus, le groupe et les supporters paieront $1\\,000\\,000$ F a raison d'une reduction de $500$ F par billet.",
      "If there are 150 more supporters, the group and supporters will pay $1,000,000$ F with a reduction of $500$ F per ticket."),
    t("En designant par $x$ le nombre de supporters du groupe initial et par $y$ le prix d'un billet :",
      "Denoting by $x$ the number of supporters in the initial group and $y$ the price of a ticket:"),
    t("a) Montrer que $x$ est solution de l'equation $(E)$. 1 pt",
      "a) Show that $x$ is a solution of equation $(E)$. 1 pt"),
    t("b) En deduire le nombre de supporters qui ont participe a ce voyage, sachant que les $150$ supporters ont accepte de se joindre au groupe initial. 1 pt",
      "b) Deduce the number of supporters who participated in the trip, knowing that the $150$ supporters agreed to join the initial group. 1 pt"),
    t("c) En deduire aussi le prix initial d'un billet. 2 pts",
      "c) Also deduce the initial price of a ticket. 2 pts"),

    sec("Partie B :", "6 points", "Part B:"),

    t("On a reparti les pointures d'un stock de $60$ paires de chaussures dans le tableau suivant :",
      "The shoe sizes of a stock of $60$ pairs of shoes are distributed in the following table:"),
    tbl("$\\begin{array}{|c|c|c|c|c|c|c|c|}\\hline \\text{Pointures} & 38 & 39 & 40 & 41 & 42 & 43 & 44 \\\\ \\hline \\text{Effectifs} & 6 & 8 & 3 & 13 & 11 & 12 & 7 \\\\ \\hline \\end{array}$",
      "$\\begin{array}{|c|c|c|c|c|c|c|c|}\\hline \\text{Shoe sizes} & 38 & 39 & 40 & 41 & 42 & 43 & 44 \\\\ \\hline \\text{Frequencies} & 6 & 8 & 3 & 13 & 11 & 12 & 7 \\\\ \\hline \\end{array}$"),
    t("1. Determiner le mode de cette serie statistique. 0,5 pt",
      "1. Determine the mode of this statistical series. 0.5 pt"),
    t("2. Calculer la pointure moyenne de ce stock de chaussures. 1 pt",
      "2. Calculate the average shoe size of this stock. 1 pt"),
    t("3. Calculer la variance et l'ecart-type de cette serie statistique. 2 pts",
      "3. Calculate the variance and standard deviation of this statistical series. 2 pts"),
    t("4. Dresser le tableau des effectifs cumules croissants et decroissants. 1 pt",
      "4. Draw the table of cumulative increasing and decreasing frequencies. 1 pt"),
    t("5. En deduire la mediane de cette serie. 1,5 pt",
      "5. Deduce the median of this series. 1.5 pt"),

    sec("Partie C :", "8 points", "Part C:"),

    t("La courbe ci-contre est une partie de la representation graphique d'une fonction numerique $f$ ayant pour ensemble de definition l'intervalle $[0\\;;3]$.",
      "The curve shown is part of the graphical representation of a numerical function $f$ with domain $[0;3]$."),
    img("/images/proba-a-2019-courbe.jpg", "Courbe representative de la fonction f sur [0;3]"),
    t("1. Par lecture graphique :",
      "1. By graphical reading:"),
    t("a. Recopier et completer le tableau suivant : 1 pt",
      "a. Copy and complete the following table: 1 pt"),
    tbl("$\\begin{array}{|c|c|c|}\\hline x & 0 & 3 \\\\ \\hline f(x) & 0 & \\\\ \\hline \\end{array}$"),
    t("b. Dresser le tableau de variation de $f$ sur $[0\\;;3]$. 1 pt",
      "b. Draw the table of variation of $f$ on $[0;3]$. 1 pt"),
    t("2) On suppose que $f$ est une fonction paire. Comment se traduit graphiquement cette propriete ? 1 pt",
      "2) Assume that $f$ is an even function. How does this property translate graphically? 1 pt"),
    t("3) Reproduire cette courbe et completer son graphique sur l'intervalle $[-3\\;;3]$. 1 pt",
      "3) Reproduce this curve and complete its graph on the interval $[-3;3]$. 1 pt"),
    t("4) Par lecture graphique :",
      "4) By graphical reading:"),
    t("a. Donner les solutions de l'equation $f(x)=0$. 1,5 pt",
      "a. Give the solutions of the equation $f(x)=0$. 1.5 pt"),
    t("b. Determiner $f(-2)$ et $f(-3)$. 1 pt",
      "b. Determine $f(-2)$ and $f(-3)$. 1 pt"),
    t("c. Resoudre l'inequation $f(x)\\ge 0$. 1,5 pt",
      "c. Solve the inequality $f(x)\\ge 0$. 1.5 pt"),
  ],

  // ===================== PROBATOIRE A 2018 =====================
  2018: [
    main("L'epreuve de mathematiques du PROBATOIRE A 2018", "Mathematics Exam - Probatoire A 2018"),

    sec("Partie A :", "6 points", "Part A:"),

    t("On considere le polynome $P(x)=x^2-3x-270$ a variable reelle $x$.",
      "Consider the polynomial $P(x)=x^2-3x-270$ with real variable $x$."),
    t("1. Calculer $P(18)$. 1 pt",
      "1. Calculate $P(18)$. 1 pt"),
    t("2. En deduire dans l'ensemble $\\mathbb{R}$, les solutions de l'equation $P(x)=0$. 1 pt",
      "2. Deduce in $\\mathbb{R}$, the solutions of the equation $P(x)=0$. 1 pt"),
    t("3. Un groupe d'eleves d'une classe de premiere decide d'entreprendre un voyage d'etude dont le cout est fixe a $54\\,000$ F. Ce cout devrait etre equitablement supporte par chaque eleve. A la derniere minute, trois eleves desistent du groupe initial et le prix a payer par chaque eleve est alors augmente de $600$ F.",
      "3. A group of first-year students decides to go on a study trip costing $54,000$ F. The cost should be equally shared by each student. At the last minute, three students withdraw from the initial group and the price per student increases by $600$ F."),
    t("On designe par $x$ le nombre d'eleves initialement retenu.",
      "Let $x$ be the number of students initially registered."),
    t("a) Montrer que $x$ verifie l'equation $x^2-3x-270=0$. 2 pts",
      "a) Show that $x$ satisfies the equation $x^2-3x-270=0$. 2 pts"),
    t("b) En deduire le nombre d'eleves initialement retenu et le prix a payer par chacun d'entre eux apres le desistement de 3 eleves. 2 pts",
      "b) Deduce the number of students initially registered and the price to pay by each after the withdrawal of 3 students. 2 pts"),

    sec("Partie B :", "6 points", "Part B:"),

    t("Le tableau ci-dessous donne les resultats d'une enquete sur les distances parcourues (en milliers de km) par 60 taxis d'une compagnie de transport urbain, quelque temps apres leur mise en circulation :",
      "The table below gives the results of a survey on distances traveled (in thousands of km) by 60 taxis of an urban transport company, some time after they were put into service:"),
    tbl("$\\begin{array}{|c|c|c|c|c|}\\hline \\text{Classes} & [0\\;;3[ & [3\\;;6[ & [6\\;;9[ & [9\\;;12[ \\\\ \\hline \\text{Centres } (x_i) & & 4{,}5 & & 10{,}5 \\\\ \\hline \\text{Effectifs } (n_i) & & 15 & 12 & \\\\ \\hline n_i x_i & 30 & & & 136{,}5 \\\\ \\hline \\end{array}$",
      "$\\begin{array}{|c|c|c|c|c|}\\hline \\text{Classes} & [0;3[ & [3;6[ & [6;9[ & [9;12[ \\\\ \\hline \\text{Centers } (x_i) & & 4.5 & & 10.5 \\\\ \\hline \\text{Frequencies } (n_i) & & 15 & 12 & \\\\ \\hline n_i x_i & 30 & & & 136.5 \\\\ \\hline \\end{array}$"),
    t("1. Recopier et completer ce tableau. 3 pts",
      "1. Copy and complete this table. 3 pts"),
    t("2. Calculer la moyenne de cette serie statistique. 1 pt",
      "2. Calculate the mean of this statistical series. 1 pt"),
    t("3. Determiner la classe modale et le mode de cette serie. 1 pt",
      "3. Determine the modal class and the mode of this series. 1 pt"),
    t("4. Construire un histogramme representant cette serie. 1 pt",
      "4. Construct a histogram representing this series. 1 pt"),

    sec("Partie C :", "8 points", "Part C:"),

    t("La courbe $(C)$ ci-contre est la representation graphique d'une fonction numerique $f$ definie sur l'intervalle $[-2\\;;4]$.",
      "The curve $(C)$ shown is the graphical representation of a numerical function $f$ defined on the interval $[-2;4]$."),
    img("/images/proba-a-2018-courbe.jpg", "Courbe representative de la fonction f sur [-2;4]"),

    subsec("I) Par lecture graphique :", "", "I) By graphical reading:"),
    t("1. Determiner les images des reels $-2$ ; $-1$ ; $1$ et $4$ par $f$. 2 pts",
      "1. Determine the images of the reals $-2$; $-1$; $1$ and $4$ by $f$. 2 pts"),
    t("2. Resoudre l'equation $f(x)=0$. 1 pt",
      "2. Solve the equation $f(x)=0$. 1 pt"),
    t("3. Dresser le tableau de variation de $f$. 1 pt",
      "3. Draw the table of variation of $f$. 1 pt"),

    subsec("II) On suppose que $f(x)=x^2+ax+b$ ou $a$ et $b$ sont des reels.", "", "II) Assume that $f(x)=x^2+ax+b$ where $a$ and $b$ are reals."),
    t("1. En utilisant les images des reels $-2$ et $1$, montrer que $a=-2$ et $b=-3$. 1,5 pt",
      "1. Using the images of $-2$ and $1$, show that $a=-2$ and $b=-3$. 1.5 pt"),
    t("2. Determiner une equation de la tangente $(T)$ a la courbe $(C)$ au point d'abscisse $3$. 1 pt",
      "2. Determine an equation of the tangent $(T)$ to the curve $(C)$ at the point with x-coordinate $3$. 1 pt"),

    subsec("III) Reproduire la courbe $(C)$ et representer graphiquement la fonction $g:x\\mapsto -f(x)$.", "", "III) Reproduce the curve $(C)$ and graphically represent the function $g:x\\mapsto -f(x)$."),
    t("1,5 pt", "1.5 pt"),
  ],

  // ===================== PROBATOIRE A 2017 =====================
  2017: [
    main("L'epreuve de mathematiques du PROBATOIRE A 2017", "Mathematics Exam - Probatoire A 2017"),

    sec("Partie A :", "6 points", "Part A:"),

    t("1. Resoudre dans $\\mathbb{R}\\times\\mathbb{R}$ le systeme d'equations suivant $(S)$ : 2 pts",
      "1. Solve in $\\mathbb{R}\\times\\mathbb{R}$ the following system of equations $(S)$: 2 pts"),
    t("$\\begin{cases} 2x+6y=11 \\\\ 4x+10y=21 \\end{cases}$"),
    t("2) Pour leurs petits dejeuners, Fanta achete 2 boites de sardine et 6 oeufs a 1 100 FCFA.",
      "2) For their breakfasts, Fanta buys 2 cans of sardines and 6 eggs for 1,100 FCFA."),
    t("Claudia achete 4 boites de sardine et 10 oeufs de meme type a 2 100 FCFA.",
      "Claudia buys 4 cans of sardines and 10 eggs of the same type for 2,100 FCFA."),
    t("Determiner le prix d'une boite de sardine et celui d'un oeuf. 2 pts",
      "Determine the price of a can of sardines and that of an egg. 2 pts"),
    t("3) Resoudre dans $\\mathbb{R}$, l'inequation $-8x^2-2x+3>0$. 2 pts",
      "3) Solve in $\\mathbb{R}$, the inequality $-8x^2-2x+3>0$. 2 pts"),

    sec("Partie B :", "6 points", "Part B:"),

    subsec("I-", "", "I-"),
    t("Une enquete menee aupres d'un groupe d'eleves de premiere litteraire sur leurs notes obtenues sur 20 en mathematiques pour le compte de l'examen blanc a donne les resultats suivants :",
      "A survey conducted among a group of first-year literary students on their mathematics grades out of 20 for the mock exam gave the following results:"),
    tbl("$\\begin{array}{|c|c|c|c|c|c|c|c|c|}\\hline \\text{Notes sur 20} & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12 \\\\ \\hline \\text{Effectifs cumules croissants} & 2 & 16 & 28 & 38 & 46 & 57 & 58 & 60 \\\\ \\hline \\end{array}$",
      "$\\begin{array}{|c|c|c|c|c|c|c|c|c|}\\hline \\text{Grades out of 20} & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12 \\\\ \\hline \\text{Cumulative increasing frequencies} & 2 & 16 & 28 & 38 & 46 & 57 & 58 & 60 \\\\ \\hline \\end{array}$"),
    t("1. Quel est l'effectif de cette classe ? 0,5 pt",
      "1. What is the total number of students in this class? 0.5 pt"),
    t("2) Dresser le tableau des effectifs et des frequences en pourcentage. 1,5 pts",
      "2) Draw the table of frequencies and percentages. 1.5 pts"),
    t("3) Recopier et completer ce tableau par la ligne des effectifs cumules decroissants. 1 pt",
      "3) Copy and complete this table with the row of cumulative decreasing frequencies. 1 pt"),
    t("4) Determiner la mediane et calculer la note moyenne des eleves de cette classe. 1 pt",
      "4) Determine the median and calculate the average grade of students in this class. 1 pt"),

    subsec("II-", "", "II-"),
    t("On suppose que dans cette classe il y a 20 filles et 40 garcons. Un comite de cinq personnes devra etre constitue pour representer la classe a l'election du president de la cooperative scolaire.",
      "Assume that in this class there are 20 girls and 40 boys. A committee of five people must be formed to represent the class in the election of the school cooperative president."),
    t("1. Quel est le nombre de comites que l'on peut constituer comprenant les eleves ayant au moins 10 sur 20 en mathematiques ? 1 pt",
      "1. How many committees can be formed with students who scored at least 10 out of 20 in mathematics? 1 pt"),
    t("2. Quel est le nombre de comites que l'on peut constituer comprenant au moins deux filles et au moins deux garcons ? 1 pt",
      "2. How many committees can be formed with at least two girls and at least two boys? 1 pt"),

    sec("Partie C :", "8 points", "Part C:"),

    t("Soit $f$ la fonction numerique definie sur l'intervalle $[-5\\;;4]$ par $f(x)=ax^2-4x+b$ ou $a$ et $b$ sont deux reels. $(\\mathcal{C})$ sa representation graphique dans le repere orthonorme $(O;\\vec{i},\\vec{j})$. Unite sur les axes 1 cm.",
      "Let $f$ be the numerical function defined on the interval $[-5;4]$ by $f(x)=ax^2-4x+b$ where $a$ and $b$ are reals. $(\\mathcal{C})$ is its graphical representation in the orthonormal coordinate system $(O;\\vec{i},\\vec{j})$. Unit on axes: 1 cm."),
    t("1. Sachant que la courbe $(\\mathcal{C})$ rencontre l'axe des ordonnees au point d'ordonnee 3 et admet au point d'abscisse $-\\dfrac{1}{2}$ une tangente de coefficient directeur 0, montrer que $a=-4$ et $b=3$. 1 pt",
      "1. Knowing that the curve $(\\mathcal{C})$ meets the y-axis at ordinate 3 and has at the point with x-coordinate $-\\dfrac{1}{2}$ a tangent with slope 0, show that $a=-4$ and $b=3$. 1 pt"),
    t("2. Determiner la fonction derivee de $f$ et etudier le sens de variations de $f$. 1 pt",
      "2. Determine the derivative of $f$ and study the direction of variation of $f$. 1 pt"),
    t("3. Dresser le tableau des variations de $f$. 1 pt",
      "3. Draw the table of variations of $f$. 1 pt"),
    t("4. Montrer que la droite d'equation $x=-\\dfrac{1}{2}$ est un axe de symetrie a la courbe $(\\mathcal{C})$. 0,5 pt",
      "4. Show that the line with equation $x=-\\dfrac{1}{2}$ is an axis of symmetry for the curve $(\\mathcal{C})$. 0.5 pt"),
    t("5. Determiner une equation de la tangente $(T)$ a la courbe $(\\mathcal{C})$ au point d'abscisse $\\dfrac{1}{2}$. 0,5 pt",
      "5. Determine an equation of the tangent $(T)$ to the curve $(\\mathcal{C})$ at the point with x-coordinate $\\dfrac{1}{2}$. 0.5 pt"),
    t("6. Resoudre l'equation $f(x)=0$ et construire la courbe $(\\mathcal{C})$ ainsi que sa tangente $(T)$. 3 pts",
      "6. Solve the equation $f(x)=0$ and construct the curve $(\\mathcal{C})$ and its tangent $(T)$. 3 pts"),
    t("7. En deduire dans le meme repere la construction de la courbe de la fonction $g$ definie par $g(x)=-f(x)$. 1 pt",
      "7. Deduce in the same coordinate system the construction of the curve of the function $g$ defined by $g(x)=-f(x)$. 1 pt"),
  ],

  // ===================== PROBATOIRE A 2016 =====================
  2016: [
    main("L'epreuve de mathematiques du PROBATOIRE A 2016", "Mathematics Exam - Probatoire A 2016"),

    sec("Partie A :", "6 points", "Part A:"),

    t("1- Resoudre dans $\\mathbb{R}^{2}$ le systeme : $\\begin{cases} 2x-y=0 \\\\ 3x+8=3y-10 \\end{cases}$ 2 pts",
      "1- Solve in $\\mathbb{R}^{2}$ the system: $\\begin{cases} 2x-y=0 \\\\ 3x+8=3y-10 \\end{cases}$ 2 pts"),
    t("2- En deduire les reels $x$ et $y$ tels que : $\\begin{cases} 2(x^{2}+5)-(y+9)=0 \\\\ 3(x^{2}+5)+8=3(y+9)-10 \\end{cases}$ 1 pt",
      "2- Deduce the reals $x$ and $y$ such that: $\\begin{cases} 2(x^{2}+5)-(y+9)=0 \\\\ 3(x^{2}+5)+8=3(y+9)-10 \\end{cases}$ 1 pt"),
    t("3- La longueur $y$ d'un rideau rectangulaire est le double de sa largeur $x$. Si l'on augmente cette largeur de $\\dfrac{8}{3}$ et diminue la longueur de $\\dfrac{10}{3}$, le rideau deviendrait un carre.",
      "3- The length $y$ of a rectangular curtain is twice its width $x$. If the width is increased by $\\dfrac{8}{3}$ and the length decreased by $\\dfrac{10}{3}$, the curtain would become a square."),
    t("a) Montrer que $x$ et $y$ verifient le systeme de la question 1). 1 pt",
      "a) Show that $x$ and $y$ satisfy the system in question 1). 1 pt"),
    t("b) En deduire les dimensions de ce rideau. 2 pts",
      "b) Deduce the dimensions of this curtain. 2 pts"),

    sec("Partie B :", "6 points", "Part B:"),

    t("Dans un programme de lutte contre les relations sexuelles precoces, le Ministere des Affaires Sociales a effectue une enquete aupres d'un groupe de jeunes. Suite a la question : << a quel age avez-vous eu votre premiere relation sexuelle ? >>, on a etabli le releve statistique suivant :",
      "In a program to combat early sexual relations, the Ministry of Social Affairs conducted a survey among a group of young people. Following the question: 'at what age did you have your first sexual relationship?', the following statistical data was established:"),
    tbl("$\\begin{array}{|c|c|c|c|c|c|}\\hline \\text{Tranche d'ages} & [12\\;;14[ & [14\\;;16[ & [16\\;;18[ & [18\\;;20[ & [20\\;;22[ \\\\ \\hline \\text{Effectif} & 18 & 6 & 15 & 14 & 7 \\\\ \\hline \\end{array}$",
      "$\\begin{array}{|c|c|c|c|c|c|}\\hline \\text{Age range} & [12;14[ & [14;16[ & [16;18[ & [18;20[ & [20;22[ \\\\ \\hline \\text{Frequency} & 18 & 6 & 15 & 14 & 7 \\\\ \\hline \\end{array}$"),
    t("1. Combien de jeunes ont pris part a cette enquete ? 1 pt",
      "1. How many young people participated in this survey? 1 pt"),
    t("2. Determiner la moyenne d'age des jeunes interrogees. 1 pt",
      "2. Determine the average age of the young people surveyed. 1 pt"),
    t("3. Construire l'histogramme de cette serie. 1 pt",
      "3. Construct the histogram of this series. 1 pt"),
    t("4. a) Combien de jeunes interroges ont-ils au moins 18 ans ? 1 pt",
      "4. a) How many surveyed young people are at least 18 years old? 1 pt"),
    t("b) Combien de jeunes interroges ont-ils moins de 14 ans ?",
      "b) How many surveyed young people are under 14?"),
    t("c) On choisit au hasard deux jeunes parmi ceux interroges pour participer a un debat televise. De combien de facons peut-on faire ce choix si l'on souhaite faire participer un jeune de moins de 14 ans et un autre d'au moins 18 ans. 2 pts",
      "c) Two young people are chosen at random from those surveyed to participate in a televised debate. In how many ways can this choice be made if one wants a young person under 14 and another at least 18? 2 pts"),

    sec("Partie C :", "8 points", "Part C:"),

    t("La courbe $(C)$ ci-dessous est une partie de la courbe representative d'une fonction $f$ sur l'intervalle $[1\\;;6]$ et $(T)$ est la tangente a $(C)$ au point d'abscisse $2$.",
      "The curve $(C)$ below is part of the representative curve of a function $f$ on the interval $[1;6]$ and $(T)$ is the tangent to $(C)$ at the point with x-coordinate $2$."),
    t("1- a) Quels sont les images de $2$ et $4$ par $f$ ? 1 pt",
      "1- a) What are the images of $2$ and $4$ by $f$? 1 pt"),
    t("b) Quels sont les antecedents de $4$ par $f$ ? 1 pt",
      "b) What are the preimages of $4$ by $f$? 1 pt"),
    t("2- Resoudre graphiquement sur l'intervalle $[1\\;;6]$ l'inequation $f(x)<4$. 2 pts",
      "2- Solve graphically on the interval $[1;6]$ the inequality $f(x)<4$. 2 pts"),
    t("3- Determiner une equation cartesienne de la tangente $(T)$. 1 pt",
      "3- Determine a Cartesian equation of the tangent $(T)$. 1 pt"),
    t("4- Sachant que $f$ est une fonction impaire, recopier et completer le tableau suivant : 1 pt",
      "4- Knowing that $f$ is an odd function, copy and complete the following table: 1 pt"),
    tbl("$\\begin{array}{|c|c|c|c|c|}\\hline x & -1 & -2 & -4 & -6 \\\\ \\hline f(x) & & & & \\\\ \\hline \\end{array}$"),
    t("5- Reproduire et completer l'autre partie de la courbe $(C)$. 1 pt",
      "5- Reproduce and complete the other part of the curve $(C)$. 1 pt"),
  ],

  // ===================== PROBATOIRE A 2015 =====================
  2015: [
    main("L'epreuve de mathematiques du PROBATOIRE A 2015", "Mathematics Exam - Probatoire A 2015"),

    sec("Partie A :", "6 points", "Part A:"),

    t("Un commercant se souvient d'avoir vendu a une date, $90$ articles constitues uniquement de crayons et de cahiers. La recette correspondante a cette vente etait de $21\\,650$ F CFA. On designe par $x$ et $y$, les nombres respectifs de crayons et de cahiers vendus ce jour la.",
      "A shopkeeper remembers having sold on a certain date, $90$ items consisting only of pencils and notebooks. The corresponding revenue from this sale was $21,650$ F CFA. Let $x$ and $y$ be the respective numbers of pencils and notebooks sold that day."),

    t("1. a) Sachant que ce commercant vendait ce jour-la, un crayon a $45$ F CFA et un cahier a $485$ FCFA, justifier que $x$ et $y$ verifient le systeme : $\\begin{cases} x+y=90 \\\\ 9x+97y=4\\,330 \\end{cases}$ 2 pts",
      "1. a) Knowing that the shopkeeper sold that day a pencil at $45$ F CFA and a notebook at $485$ FCFA, justify that $x$ and $y$ satisfy the system: $\\begin{cases} x+y=90 \\\\ 9x+97y=4,330 \\end{cases}$ 2 pts"),
    t("b) En deduire le nombre de cahiers et de crayons vendus ce jour-la par le commercant. 1 pt",
      "b) Deduce the number of notebooks and pencils sold that day by the shopkeeper. 1 pt"),

    t("2. Ces cahiers coutent aujourd'hui $550$ FCFA la piece apres une augmentation de $t\\%$ ou $t$ est un nombre rationnel.",
      "2. These notebooks now cost $550$ FCFA each after an increase of $t\\%$ where $t$ is a rational number."),
    t("a) Justifier que $t$ est solution de l'equation : $485+4{,}85t=550$. 1 pt",
      "a) Justify that $t$ is a solution of the equation: $485+4.85t=550$. 1 pt"),
    t("b) En deduire une valeur approchee de $t$ a $10^{-1}$ pres par defaut. 2 pts",
      "b) Deduce an approximate value of $t$ to $10^{-1}$ by default. 2 pts"),

    sec("Partie B :", "6 points", "Part B:"),

    t("On s'est interesse aux notes sur $20$ en mathematiques des candidats a un concours. Les resultats de cette enquete, regroupes en classes sont consignes dans le tableau ci-dessous :",
      "We looked at the mathematics grades out of $20$ of candidates for a competition. The results of this survey, grouped into classes, are recorded in the table below:"),
    tbl("$\\begin{array}{|c|c|c|c|c|c|}\\hline \\text{Classes des notes} & [0\\;;4[ & [4\\;;8[ & [8\\;;12[ & [12\\;;16[ & [16\\;;20[ \\\\ \\hline \\text{Nombre d'eleves } (n_i) & 25 & 30 & 20 & 15 & 10 \\\\ \\hline \\end{array}$",
      "$\\begin{array}{|c|c|c|c|c|c|}\\hline \\text{Grade classes} & [0;4[ & [4;8[ & [8;12[ & [12;16[ & [16;20[ \\\\ \\hline \\text{Number of students } (n_i) & 25 & 30 & 20 & 15 & 10 \\\\ \\hline \\end{array}$"),
    t("1. Donner la ou les classe(s) modale(s) de cette serie statistique. 1 pt",
      "1. Give the modal class(es) of this statistical series. 1 pt"),
    t("2. Calculer la moyenne et l'ecart-type de cette serie (on donnera le resultat a $10^{-2}$ pres). 1 pt",
      "2. Calculate the mean and standard deviation of this series (give the result to $10^{-2}$). 1 pt"),
    t("3. Recopier ce tableau et le completer par la ligne des effectifs cumules croissants. 2 pts",
      "3. Copy this table and complete it with the row of cumulative increasing frequencies. 2 pts"),
    t("4. On voudrait attribuer un prix a un groupe de $4$ candidats simultanement choisis au hasard parmi les $10$ ayant eu une note d'au moins $16/20$. On admet que $4$ de ces $10$ candidats sont des dames.",
      "4. A prize is to be awarded to a group of $4$ candidates simultaneously chosen at random from the $10$ who scored at least $16/20$. It is given that $4$ of these $10$ candidates are women."),
    t("a) De combien de facons peut-on choisir le groupe a primer ? 1 pt",
      "a) In how many ways can the prize group be chosen? 1 pt"),
    t("b) De combien de facons peut se faire le choix du groupe a primer s'il faut qu'il comporte autant de dames que d'hommes ? 2 pts",
      "b) In how many ways can the prize group be chosen if it must contain equal numbers of women and men? 2 pts"),

    sec("Partie C :", "8 points", "Part C:"),

    t("Soit $f$ la fonction definie dans $[-2\\;;1]$ par $f(x)=-2x^2-2x+\\dfrac{3}{2}$. On designe par $(\\mathcal{C}_f)$ sa courbe representative dans un repere orthonorme $(O;\\vec{i},\\vec{j})$.",
      "Let $f$ be the function defined on $[-2;1]$ by $f(x)=-2x^2-2x+\\dfrac{3}{2}$. $(\\mathcal{C}_f)$ denotes its representative curve in an orthonormal coordinate system $(O;\\vec{i},\\vec{j})$."),
    t("1. Calculer les limites de $f$ aux bornes de son ensemble de definition. 1 pt",
      "1. Calculate the limits of $f$ at the bounds of its domain. 1 pt"),
    t("2. a) Calculer $f'(x)$. 1 pt",
      "2. a) Calculate $f'(x)$. 1 pt"),
    t("b) En deduire que $f'(x)>0 \\Leftrightarrow x\\in\\left[-2\\;;-\\dfrac{1}{2}\\right[$. 1 pt",
      "b) Deduce that $f'(x)>0 \\Leftrightarrow x\\in\\left[-2;-\\dfrac{1}{2}\\right[$. 1 pt"),
    t("3. Dresser le tableau de variation de $f$. 1,5 pt",
      "3. Draw the table of variation of $f$. 1.5 pt"),
    t("4. a) Montrer que $x\\in[-2\\;;1] \\Leftrightarrow (-1-x)\\in[-2\\;;1]$. 1,5 pt",
      "4. a) Show that $x\\in[-2;1] \\Leftrightarrow (-1-x)\\in[-2;1]$. 1.5 pt"),
    t("b) Tracer $(\\mathcal{C}_f)$. 2 pts",
      "b) Draw $(\\mathcal{C}_f)$. 2 pts"),
  ],

  // ===================== PROBATOIRE A 2014 =====================
  2014: [
    main("L'epreuve de mathematiques du PROBATOIRE A 2014", "Mathematics Exam - Probatoire A 2014"),

    sec("Partie A :", "6 points", "Part A:"),

    t("1. a) Resoudre dans $\\mathbb{R}^2$, le systeme d'inconnues $(x,y)$ suivant : $\\begin{cases} 2x+3y=7\\,450 \\\\ x+y=3\\,125 \\end{cases}$ 2 pts",
      "1. a) Solve in $\\mathbb{R}^2$, the following system with unknowns $(x,y)$: $\\begin{cases} 2x+3y=7,450 \\\\ x+y=3,125 \\end{cases}$ 2 pts"),
    t("b) En deduire les reels $x$ et $y$ tels que : $\\begin{cases} \\dfrac{2(100x-75)+3(y+798)}{y}=7\\,450 \\\\ \\dfrac{100x-75+(y+798)}{y}=3\\,125 \\end{cases}$ 2 pts",
      "b) Deduce the reals $x$ and $y$ such that: $\\begin{cases} \\dfrac{2(100x-75)+3(y+798)}{y}=7,450 \\\\ \\dfrac{100x-75+(y+798)}{y}=3,125 \\end{cases}$ 2 pts"),

    t("2. Assomo achete 2 machettes et 3 houes pour un montant total de $7\\,450$ FCFA. Si elle avait plutot achete 3 machettes et 3 houes aux memes prix unitaires, elle aurait depense $9\\,375$ FCFA. On designe par $x$ le prix d'une machette achetee et par $y$, celui d'une houe.",
      "2. Assomo buys 2 machetes and 3 hoes for a total of $7,450$ FCFA. If she had instead bought 3 machetes and 3 hoes at the same unit prices, she would have spent $9,375$ FCFA. Let $x$ be the price of a machete and $y$ the price of a hoe."),
    t("a) Verifier que $x$ et $y$ verifient le systeme : $\\begin{cases} 2x+3y=7\\,450 \\\\ x+y=3\\,125 \\end{cases}$ 1 pt",
      "a) Verify that $x$ and $y$ satisfy the system: $\\begin{cases} 2x+3y=7,450 \\\\ x+y=3,125 \\end{cases}$ 1 pt"),
    t("b) En deduire le prix d'une machette et celui d'une houe. 1 pt",
      "b) Deduce the price of a machete and that of a hoe. 1 pt"),

    sec("Partie B :", "6 points", "Part B:"),

    t("Des responsables d'un etablissement scolaire ont note durant une semaine, le temps passe par chaque eleve d'une classe de 1ere A4 au centre de ressources multimedia. Les resultats de cette enquete sont synthetises dans le tableau ci-dessous :",
      "School officials recorded during a week the time spent by each student of a 1st year A4 class at the multimedia resource center. The results are summarized in the table below:"),
    tbl("$\\begin{array}{|c|c|c|c|c|}\\hline \\text{Intervalles de temps passe en heure} & [0\\;;2[ & [2\\;;4[ & [4\\;;5[ & [5\\;;6] \\\\ \\hline \\text{Effectifs des eleves} & 5 & 45 & 10 & 20 \\\\ \\hline \\end{array}$",
      "$\\begin{array}{|c|c|c|c|c|}\\hline \\text{Time intervals in hours} & [0;2[ & [2;4[ & [4;5[ & [5;6] \\\\ \\hline \\text{Number of students} & 5 & 45 & 10 & 20 \\\\ \\hline \\end{array}$"),
    t("1. Calculer la moyenne de la serie statistique ainsi definie. 2 pts",
      "1. Calculate the mean of this statistical series. 2 pts"),
    t("2. Dresser le tableau des effectifs cumules croissants. 1 pt",
      "2. Draw the table of cumulative increasing frequencies. 1 pt"),
    t("3. Determiner le nombre d'eleves qui ont passe au moins 4 heures ou au moins deux heures dans ce centre multimedia. 1 pt",
      "3. Determine the number of students who spent at least 4 hours or at least two hours in this multimedia center. 1 pt"),
    t("4. 5 eleves de cette classe dont 3 filles sont candidats a l'election du bureau de cette classe constitue dans l'ordre d'un chef de classe, de son adjoint et d'un charge des affaires sportives. On admet qu'il n'y a pas de cumul de poste.",
      "4. 5 students of this class including 3 girls are candidates for the class office consisting in order of a class leader, a deputy and a sports officer. No one can hold more than one position."),
    t("a) Combien peut-on avoir de bureaux ayant exactement une fille ? 1 pt",
      "a) How many offices can have exactly one girl? 1 pt"),
    t("b) Combien peut-on avoir de bureaux ayant exactement une seule fille qui en plus occupe le poste de chef de classe ? 1 pt",
      "b) How many offices can have exactly one girl who also holds the position of class leader? 1 pt"),

    sec("Partie C :", "8 points", "Part C:"),

    t("La courbe $(C)$ ci-contre est la representation graphique dans un repere orthonorme $(O,I,J)$ d'une fonction $f$ definie dans l'intervalle $[-1\\;;5]$ par $f(x)=x^2+bx+c$ ou $b$ et $c$ sont des constantes reelles.",
      "The curve $(C)$ shown is the graphical representation in an orthonormal coordinate system $(O,I,J)$ of a function $f$ defined on the interval $[-1;5]$ by $f(x)=x^2+bx+c$ where $b$ and $c$ are real constants."),
    t("Repondre aux questions 1 et 2 par lecture graphique.",
      "Answer questions 1 and 2 by graphical reading."),
    t("1. a) Determiner l'image de l'intervalle $[1\\;;4]$ par $f$. 1 pt",
      "1. a) Determine the image of the interval $[1;4]$ by $f$. 1 pt"),
    t("b) Donner les antecedents de $8$ par $f$. 0,75 pt",
      "b) Give the preimages of $8$ by $f$. 0.75 pt"),
    t("c) Determiner l'ensemble des reels $x$ de l'intervalle $[-1\\;;5]$ tels que $f(x)>3$. 0,75 pt",
      "c) Determine the set of reals $x$ in the interval $[-1;5]$ such that $f(x)>3$. 0.75 pt"),
    t("2. a) Donner l'image de $0$ par $f$ et en deduire que $c=3$. 1 pt",
      "2. a) Give the image of $0$ by $f$ and deduce that $c=3$. 1 pt"),
    t("b) Donner l'image de $1$ par $f$. 0,5 pt",
      "b) Give the image of $1$ by $f$. 0.5 pt"),
    t("c) En deduire que pour tout reel $x$ de l'intervalle $[-1\\;;5]$, $f(x)=x^2-4x+3$. 0,75 pt",
      "c) Deduce that for all real $x$ in the interval $[-1;5]$, $f(x)=x^2-4x+3$. 0.75 pt"),
    t("3. Calculer $f'(x)$ et etudier les variations de $f$. 1,5 pt",
      "3. Calculate $f'(x)$ and study the variations of $f$. 1.5 pt"),
    t("4. Reproduire $(C)$ et en deduire dans le meme repere, la courbe de la fonction $h$ definie par $h(x)=-f(x)$. 1,75 pt",
      "4. Reproduce $(C)$ and deduce in the same coordinate system, the curve of the function $h$ defined by $h(x)=-f(x)$. 1.75 pt"),
  ],

  // ===================== PROBATOIRE A 2013 =====================
  2013: [
    main("L'epreuve de mathematiques du PROBATOIRE A 2013", "Mathematics Exam - Probatoire A 2013"),

    sec("Partie A :", "6 points", "Part A:"),

    t("1. a) Resoudre dans $\\mathbb{N}$, l'inequation : $\\dfrac{10x+500}{x}\\le 15$. 2 pts",
      "1. a) Solve in $\\mathbb{N}$, the inequality: $\\dfrac{10x+500}{x}\\le 15$. 2 pts"),
    t("b) Amidou vend des gateaux dans la cantine de votre etablissement. Sachant que le prix de revient d'un gateau est donne en francs par la relation : $R(n)=\\dfrac{10n+500}{n}$ (designant le nombre de gateaux a vendre), a partir de quel nombre de gateaux ce prix de revient sera-t-il inferieur a 15 F ? 1 pt",
      "b) Amidou sells cakes in your school canteen. Knowing that the cost price of a cake is given in francs by the relation: $R(n)=\\dfrac{10n+500}{n}$ (denoting the number of cakes to sell), from what number of cakes will this cost price be less than 15 F? 1 pt"),

    t("3. Resoudre dans $\\mathbb{R}$ l'equation : $x^2-32x+175=0$. 1,5 pt",
      "3. Solve in $\\mathbb{R}$ the equation: $x^2-32x+175=0$. 1.5 pt"),

    t("4. Trouver deux nombres $a$ et $b$ verifiant le systeme : $\\begin{cases} a+b=320 \\\\ ab=17\\,500 \\end{cases}$ 1,5 pt",
      "4. Find two numbers $a$ and $b$ satisfying the system: $\\begin{cases} a+b=320 \\\\ ab=17,500 \\end{cases}$ 1.5 pt"),

    sec("Partie B :", "6 points", "Part B:"),

    t("Dans un etablissement, on a mesure la taille de 250 garcons de 10 ans. Le resultat est consigne dans le tableau suivant :",
      "In a school, the height of 250 boys aged 10 was measured. The result is recorded in the following table:"),
    tbl("$\\begin{array}{|c|c|c|c|c|c|}\\hline \\text{Tailles en cm} & [125\\;;130[ & [130\\;;135[ & [135\\;;140[ & [140\\;;145[ & [145\\;;150[ \\\\ \\hline \\text{Effectifs } (n_i) & 15 & 57 & 86 & 66 & 26 \\\\ \\hline \\text{Centres } (x_i) & 127{,}5 & & & & \\\\ \\hline n_i x_i & 1912{,}5 & & & & 3835 \\\\ \\hline \\text{Frequences } (f_i) & & 22{,}8 & & & \\\\ \\hline \\end{array}$",
      "$\\begin{array}{|c|c|c|c|c|c|}\\hline \\text{Heights in cm} & [125;130[ & [130;135[ & [135;140[ & [140;145[ & [145;150[ \\\\ \\hline \\text{Frequencies } (n_i) & 15 & 57 & 86 & 66 & 26 \\\\ \\hline \\text{Centers } (x_i) & 127.5 & & & & \\\\ \\hline n_i x_i & 1912.5 & & & & 3835 \\\\ \\hline \\text{Relative freq. } (f_i) & & 22.8 & & & \\\\ \\hline \\end{array}$"),
    t("1. Determiner l'amplitude des classes. 0,5 pt",
      "1. Determine the class width. 0.5 pt"),
    t("2. Recopier et completer le tableau ci-dessus. 3 pts",
      "2. Copy and complete the table above. 3 pts"),
    t("3. Quelle est la classe modale de cette serie statistique ? 0,5 pt",
      "3. What is the modal class of this statistical series? 0.5 pt"),
    t("4. En utilisant les centres des classes, calculer la taille moyenne. 1 pt",
      "4. Using the class centers, calculate the average height. 1 pt"),
    t("5. On veut completer l'equipe minime de football de l'etablissement en choisissant 4 eleves ayant une taille comprise entre 125 et 130 cm. Pour trouver le nombre de choix possibles, votre camarade propose quatre formules : 1 pt",
      "5. To complete the school's junior football team by choosing 4 students with heights between 125 and 130 cm. To find the number of possible choices, your classmate proposes four formulas: 1 pt"),
    t("a) $C_{125}^{4}$ ; b) $4$ ; c) $C_{15}^{4}$ ; d) $A_{15}^{4}$."),
    t("Parmi ces formules une seule est juste, recopier la sur votre feuille de composition.",
      "Among these formulas only one is correct, copy it on your answer sheet."),

    sec("Partie C :", "8 points", "Part C:"),

    t("Soit $f$ la fonction numerique de la variable reelle $x$ definie sur $[0\\;;4]$ par : $f(x)=x^2-4x+6$ et $C_f$ sa courbe representative, dans le plan muni d'un repere orthonorme $(O;\\vec{i};\\vec{j})$.",
      "Let $f$ be the numerical function of real variable $x$ defined on $[0;4]$ by: $f(x)=x^2-4x+6$ and $C_f$ its representative curve, in the plane equipped with an orthonormal coordinate system $(O;\\vec{i};\\vec{j})$."),
    t("1. Calculer les reels suivants : $f\\left(\\dfrac{1}{2}\\right)$ ; $f(2)$ et $f(1)$. 1 pt",
      "1. Calculate the following reals: $f\\left(\\dfrac{1}{2}\\right)$; $f(2)$ and $f(1)$. 1 pt"),
    t("2. Calculer $f'(x)$ et determiner son signe dans $[0\\;;4]$. 1 pt",
      "2. Calculate $f'(x)$ and determine its sign on $[0;4]$. 1 pt"),
    t("3. Donner le tableau de variations de la fonction $f$ dans l'intervalle $[0\\;;4]$. 1 pt",
      "3. Give the table of variations of the function $f$ on the interval $[0;4]$. 1 pt"),
    t("4. Ecrire les equations cartesiennes des tangentes $(T)$ et $(T')$ a la courbe $C_f$ aux points d'abscisses respectives $x_0=1$ et $x_1=2$. 1 pt",
      "4. Write the Cartesian equations of the tangents $(T)$ and $(T')$ to the curve $C_f$ at points with x-coordinates $x_0=1$ and $x_1=2$ respectively. 1 pt"),
    t("5. Tracer dans le meme repere les tangentes $(T)$, $(T')$ et la courbe $C_f$. 3 pts",
      "5. Draw in the same coordinate system the tangents $(T)$, $(T')$ and the curve $C_f$. 3 pts"),
    t("6. Soit $g$ la fonction numerique de la variable reelle $x$ definie par $g(x)=f(x)-6$. Tracer la courbe $C_g$ dans le meme repere que $C_f$. 1 pt",
      "6. Let $g$ be the numerical function of real variable $x$ defined by $g(x)=f(x)-6$. Draw the curve $C_g$ in the same coordinate system as $C_f$. 1 pt"),
  ],

  // ===================== PROBATOIRE A 2012 =====================
  2012: [
    main("L'epreuve de mathematiques du PROBATOIRE A 2012", "Mathematics Exam - Probatoire A 2012"),

    sec("Partie A :", "6 points", "Part A:"),

    t("1. Resoudre dans $\\mathbb{R}$ l'equation $x^2-60x+800=0$. 2 pts",
      "1. Solve in $\\mathbb{R}$ the equation $x^2-60x+800=0$. 2 pts"),
    t("2. Resoudre dans $\\mathbb{R}$ l'inequation $x^2-60x+800<0$. 1 pt",
      "2. Solve in $\\mathbb{R}$ the inequality $x^2-60x+800<0$. 1 pt"),
    t("3. Resoudre dans $\\mathbb{R}$ le systeme : 1,5 pt",
      "3. Solve in $\\mathbb{R}$ the system: 1.5 pt"),
    t("$\\begin{cases} 3x+2y=360 \\\\ 3x-4y=0 \\end{cases}$"),
    t("4. Omar a utilise 360 metres de fil barbele pour entourer son champ de forme rectangulaire. On sait d'autre part qu'il a mis trois rangees de fil dans le sens de la longueur et deux rangees dans le sens de la largeur.",
      "4. Omar used 360 meters of barbed wire to surround his rectangular field. It is also known that he placed three rows of wire along the length and two rows along the width."),
    t("Soit $x$ la longueur et $y$ la largeur de ce terrain. On suppose que $x$ et $y$ sont respectivement proportionnelles aux nombres 4 et 30. Trouver les dimensions de ce terrain. 1,5 pt",
      "Let $x$ be the length and $y$ the width of this land. Assuming that $x$ and $y$ are respectively proportional to the numbers 4 and 30. Find the dimensions of this land. 1.5 pt"),

    sec("Partie B :", "6 points", "Part B:"),

    subsec("I-", "", "I-"),
    t("Calculer en fonction de $x$ entier naturel les nombres $C_x^2$ et $A_x^2$. 1 pt",
      "Calculate as a function of natural integer $x$ the numbers $C_x^2$ and $A_x^2$. 1 pt"),

    subsec("II-", "", "II-"),
    t("Un groupe de danse de tam-tam est constitue de 5 filles et de 6 garcons. Pour constituer ce groupe, on a preselectionne 10 filles dont Anne et 10 garcons dont Jean Pierre.",
      "A tam-tam dance group consists of 5 girls and 6 boys. To form this group, 10 girls including Anne and 10 boys including Jean Pierre were preselected."),
    t("1. Combien de groupes peut-on former avec tous ces preselectionnes ? 1,5 pt",
      "1. How many groups can be formed with all these preselected members? 1.5 pt"),
    t("2. Combien de groupes de danse peut-on former sachant que Anne et Jean connus comme meilleurs danseurs sont selectionnes d'office ? 1,5 pt",
      "2. How many dance groups can be formed knowing that Anne and Jean, known as the best dancers, are automatically selected? 1.5 pt"),
    t("3. Combien de groupes de danse peut-on former sachant qu'une seule des personnes citees (Anne et Jean Pierre) est selectionnee ? 2 pts",
      "3. How many dance groups can be formed knowing that only one of the mentioned persons (Anne and Jean Pierre) is selected? 2 pts"),

    sec("Partie C :", "8 points", "Part C:"),

    t("On considere la fonction numerique $f$ d'une variable reelle $x$ definie sur l'intervalle $[0\\;;2[\\;\\cup\\;]2\\;;4]$ par : $f(x)=\\dfrac{3}{2-x}$. $(C)$ est la courbe representative de $f$ dans le repere orthonorme $(O,\\vec{i},\\vec{j})$.",
      "Consider the numerical function $f$ of real variable $x$ defined on the interval $[0;2[\\;\\cup\\;]2;4]$ by: $f(x)=\\dfrac{3}{2-x}$. $(C)$ is the representative curve of $f$ in the orthonormal coordinate system $(O,\\vec{i},\\vec{j})$."),
    t("1. Quel est l'ensemble $D$ de definition de $f$ ? 1 pt",
      "1. What is the domain $D$ of $f$? 1 pt"),
    t("2. Calculer $\\displaystyle\\lim_{x\\to 2^-} f(x)$ et $\\displaystyle\\lim_{x\\to 2^+} f(x)$. 1 pt",
      "2. Calculate $\\displaystyle\\lim_{x\\to 2^-} f(x)$ and $\\displaystyle\\lim_{x\\to 2^+} f(x)$. 1 pt"),
    t("3. Donner une equation cartesienne de l'asymptote a la courbe representative de $f$. 1 pt",
      "3. Give a Cartesian equation of the asymptote to the representative curve of $f$. 1 pt"),
    t("4. Calculer $f'(x)$ ou $f'$ est la fonction derivee de $f$. 1 pt",
      "4. Calculate $f'(x)$ where $f'$ is the derivative of $f$. 1 pt"),
    t("5. Etudier le signe de $f'$ et dresser le tableau de variation de $f$. 1 pt",
      "5. Study the sign of $f'$ and draw the table of variation of $f$. 1 pt"),
    t("6. Ecrire une equation cartesienne de la tangente $(T)$ a $(C)$ au point d'abscisse $3$. 1 pt",
      "6. Write a Cartesian equation of the tangent $(T)$ to $(C)$ at the point with x-coordinate $3$. 1 pt"),
    t("7. Tracer dans le repere $(O,\\vec{i},\\vec{j})$ la droite $(T)$ et la courbe $(C)$. 2 pts",
      "7. Draw in the coordinate system $(O,\\vec{i},\\vec{j})$ the line $(T)$ and the curve $(C)$. 2 pts"),
  ],

  // ===================== PROBATOIRE A 2011 =====================
  2011: [
    main("L'epreuve de mathematiques du PROBATOIRE A 2011", "Mathematics Exam - Probatoire A 2011"),

    sec("Partie A :", "6 points", "Part A:"),

    t("Dans le tableau ci-dessous, pour chacune des affirmations / questions inscrites dans la colonne de gauche, une seule des quatre reponses qui vous sont proposees est exacte ; preciser (sans demonstration) pour chaque question / affirmation, laquelle.",
      "In the table below, for each statement/question in the left column, only one of the four proposed answers is correct; specify (without proof) for each question/statement, which one."),
    t("$2\\times 3=6$ points"),

    t("1) Un champ rectangulaire a un perimetre de $86$ m et une aire de $450$ m$^2$ ; ses dimensions sont solutions de l'equation du $2^{\\text{nd}}$ degre suivante : 2 pts",
      "1) A rectangular field has a perimeter of $86$ m and an area of $450$ m$^2$; its dimensions are solutions of the following quadratic equation: 2 pts"),
    t("a) $x^2+43x+450=0$ ; b) $x^2-43x+450=0$ ; c) $x^2-86x+450=0$ ; d) $x^2-450x-43=0$."),

    t("2) L'equation du $2^{\\text{nd}}$ degre $x^2-2x\\sqrt{2}+\\sqrt{3}=0$ : 2 pts",
      "2) The quadratic equation $x^2-2x\\sqrt{2}+\\sqrt{3}=0$: 2 pts"),
    t("a) Admet une racine double ; b) Admet deux racines de meme signe ; c) Admet deux racines de signes contraires ; d) N'admet pas de racines.",
      "a) Has a double root; b) Has two roots of the same sign; c) Has two roots of opposite signs; d) Has no roots."),

    t("3) L'ensemble des solutions de l'inequation $x^2-2x-8<0$ est l'intervalle : 2 pts",
      "3) The solution set of the inequality $x^2-2x-8<0$ is the interval: 2 pts"),
    t("a) $[-2\\;;4[$ ; b) $[-2\\;;4]$ ; c) $]-2\\;;4]$ ; d) $]-2\\;;4[$."),

    sec("Partie B :", "6 points", "Part B:"),

    t("Un chef de caisse d'une banque de la place comptabilise les cheques payes et leurs montants respectifs a la fin d'une journee ; il les a regroupes selon le tableau suivant :",
      "A head cashier of a local bank tallies the paid checks and their respective amounts at the end of a day; he grouped them in the following table:"),
    tbl("$\\begin{array}{|c|c|c|c|c|c|c|c|}\\hline \\text{Groupe de montants} & [10\\;;30[ & [30\\;;50[ & [50\\;;70[ & [70\\;;90[ & [90\\;;110[ & [110\\;;130[ & [130\\;;150[ \\\\ \\hline \\text{Effectifs} & 10 & 16 & 25 & 45 & 35 & 20 & 9 \\\\ \\hline \\end{array}$",
      "$\\begin{array}{|c|c|c|c|c|c|c|c|}\\hline \\text{Amount groups} & [10;30[ & [30;50[ & [50;70[ & [70;90[ & [90;110[ & [110;130[ & [130;150[ \\\\ \\hline \\text{Frequencies} & 10 & 16 & 25 & 45 & 35 & 20 & 9 \\\\ \\hline \\end{array}$"),
    t("Les montants des cheques sont exprimes en dizaines de milliers de francs CFA.",
      "The check amounts are expressed in tens of thousands of CFA francs."),
    t("1. Combien de cheques ont-ils ete payes au cours de cette journee ? 1 pt",
      "1. How many checks were paid during this day? 1 pt"),
    t("2. Tracer l'histogramme de cette serie statistique et son polygone des effectifs. 2 pts",
      "2. Draw the histogram of this statistical series and its frequency polygon. 2 pts"),
    t("3. Calculer le montant moyen des cheques payes au cours de la journee, la variance et l'ecart type de cette serie statistique. 3 pts",
      "3. Calculate the average amount of checks paid during the day, the variance and standard deviation of this statistical series. 3 pts"),

    sec("Partie C :", "8 points", "Part C:"),

    t("On considere la fonction numerique $g$ de la variable reelle $x$ definie dans $[-3\\;;3]$ par : $g(x)=\\dfrac{2x+4}{x+1}$.",
      "Consider the numerical function $g$ of real variable $x$ defined on $[-3;3]$ by: $g(x)=\\dfrac{2x+4}{x+1}$."),
    t("$(C)$ designe la courbe representative de $g$ dans un repere orthonorme $(O,\\vec{i},\\vec{j})$.",
      "$(C)$ denotes the representative curve of $g$ in an orthonormal coordinate system $(O,\\vec{i},\\vec{j})$."),
    t("1. Calculer $g(0)$, $g(-2)$ et $g(1)$. 1 pt",
      "1. Calculate $g(0)$, $g(-2)$ and $g(1)$. 1 pt"),
    t("2. Calculer les limites de $g$ quand $x$ tend vers $-1$. 1 pt",
      "2. Calculate the limits of $g$ as $x$ tends to $-1$. 1 pt"),
    t("3. Calculer $g'(x)$ et dresser le tableau de variation de $g$. 3 pts",
      "3. Calculate $g'(x)$ and draw the table of variation of $g$. 3 pts"),
    t("4. Trouver les coordonnees des points d'intersection de $(C)$ avec les axes. 1 pt",
      "4. Find the coordinates of the intersection points of $(C)$ with the axes. 1 pt"),
    t("5. Tracer dans le repere $(O,\\vec{i},\\vec{j})$ la courbe $(C)$. 2 pts",
      "5. Draw in the coordinate system $(O,\\vec{i},\\vec{j})$ the curve $(C)$. 2 pts"),
  ],

}
